### ISSUE TITLE
how to change the hostname ?

### ISSUE THREAD

**Issue by gtinside** [andypetrella/spark-notebook#101]
Hi ,

The notebook server always starts on 0.0.0.0. I have tried various things such as putting in a .conf file with property hostname="<ip>" or even passing in the args while running play but all in vain. Can someone help me here ?

Regards,
Gaurav

**Comment by andypetrella** [comment]
Hello,

Could you try launching it this way maybe?
```{shell}
# example using hadoop 2.4.0
unzip spark-notebook-0.2.0-spark-1.2.0-hadoop-2.4.0.zip
cd spark-notebook-0.2.0-spark-1.2.0-hadoop-2.4.0
./bin/spark-notebook -Dhttp.address="example.com"
```

cheers,
andy

**Comment by andypetrella** [comment]
hello @gtinside, you can try with the new release 0.2.11 now.
Since I tested it and it works, I'm going to close this issue but feel free to reopen if it doesn't work for you!
