### ISSUE TITLE
Bar Chart integration

### ISSUE THREAD

**Issue by axlpado** [andypetrella/spark-notebook#104]
Hi andy,

what about integrate a fast way to show results in a bar chart ( or other kinds of charts ) like zeppelin, without code it?

if you want I can take this task, but I would like to chat with you about this. I think that D3 could be a good choice.

Let me know

Paolo

**Comment by andypetrella** [comment]
You read my mind...
For now, there the WISP that can do that quite easily. The sad part being that it's relying on highcharts.
Although this library is very cool, it's non free!

So having such features enabled using native D3 or a component one (like NVD3 or C3js) would be awesome imo.

Let's discuss that on gitter right? Then we'll put the conclusion here.

thanks for your proposal!

**Comment by andypetrella** [comment]
\o/
