### ISSUE TITLE
Spark-1.2.1 is out (and repl jar is published!)

### ISSUE THREAD

**Issue by tylerprete** [andypetrella/spark-notebook#105]
Just an FYI if you didn't see the announcement. Would be cool to get a build out supporting it.

**Comment by andypetrella** [comment]
yep I saw... like 10 minutes after my release :-).

Anyway, that's cool.
What I'll do is
- adding a system prop that can be used (-D or -J) to specify the hadoop and spark versions
- trying it with this new version then publish it!

But today, it'll be hard, though :-/

**Comment by tylerprete** [comment]
Cool. No rush :)

**Comment by andypetrella** [comment]
This is finally done, I'm currently creating a new release with 1.2.1 support + hadoop 2.2 + scala 2.11.
pheww :-D
