### ISSUE TITLE
Highlighting triple quotes not working as expected

### ISSUE THREAD

**Issue by lucaventurini** [andypetrella/spark-notebook#106]
Try with this:

```scala
val patternName : scala.util.matching.Regex = """.*<name>(.*)</name>.*""".r
val patternCountry = """.*<country>(.*)</country>.*""".r
println("Hi Andy!")
```

**Comment by andypetrella** [comment]
Indeed! Will look at what codemirror propose for that!

**Comment by andypetrella** [comment]
Okay, doesn't work either with the last version of codemirror => http://codemirror.net/mode/clike/index.html 

So I guess, an issue on the tool is necessary.

Thanks for reporting!

**Comment by andypetrella** [comment]
there we go
https://github.com/codemirror/CodeMirror/issues/3078
