### ISSUE TITLE
Integration with Tachyon

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#121]
## What
Keep track of one or several tachyon instances for some purposes (examples will be presented below).

### Local start
When the server is started it can, if conf asks for it, start a local Tachyon instance and register the connection string to it.

### Cluster connection
Add a *add* button to register a non-local tachyon cluster.

### Browse the available dataset (raw or prepared)
In the notebook we could have an area showing the tachyon available resources for doing analysis with.

**Note:** this is a nice to have for the moment, because requires much effort to have thigh integration with Tachyon APIs and so fort → plus the required UI and notebook API (like the dbfs in databricks cloud).

### Share the work
In notebook **A** data can be processed for a specific use case.

Then in notebook **B**, this processed data could be reused for a different use case or different analyses for the same use case.

Or this can be helpful to have several models tested in a different notebook (single notebook is generally a mess). Then this will allow avoid the worst case where data munging has to be redone in each notebook (single current option in local mode).

### Integration
This would be very helpful for integration with https://github.com/mighdoll/sparkle for instance.

After discussions with @mighdoll this would give an opportunity for a notebook a sparkle to evolve in an interesting way + allow good and efficient interactions.

**Comment by andypetrella** [comment]
the integration has landed now, so it's rather easy to use tachyon to either cache stuffs or share data/results.
It is a good step further an integration with the @mighdoll's project, [sparkle](https://github.com/mighdoll/sparkle)

**Comment by mighdoll** [comment]
sounds great @andypetrella, it'll be fun to connect these two together
