### ISSUE TITLE
Auto plotting: adding a way to customize

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#126]
For now the non classical cases are displaying data as a table. Which is already really great, however we have all the information to generate also a `form` (or alike) that would the user choose which rendering he'd like for the data.

Simple example, 
```scala
case class Row(id:Int, category:String, value:Double)
val rows:List[DataPoint]
``` 
The above's list will be rendered with a table with three columns.
We could also add a form that would let us pick (at first, it can be really elaborated) 2 fields and show the current tabs for them.
So in case the user picks `category` and `value`, we'd show the full _table_,  the _pie_ chart and the _bar_ chart.

(see also #37 for some discussions about this)

**Comment by andypetrella** [comment]
cc'ing @axlpado :-D

**Comment by axlpado** [comment]
what about putting a kind of picker on all column headers of the table? So just clicking on the column header you can choose what dimensions visualize in the charts. Maybe we could handle it just client side with js.
The table will be always present so it's a good starting point for user to choose fields.

P.

**Comment by andypetrella** [comment]
I like that! :+1:

**Comment by andypetrella** [comment]
There are the `Chart` implementation in the widgets package that allows some customization using a pair of fields that will draw the asked plot.

Let's close this now, since `DiyChart` enables more control over the javascript.

However, 
* documentation is needed
* create a dedicated submodule → plus Api export is most wanted!
