### ISSUE TITLE
tune the yarn integration

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#133]
for now the yarn integration relies on stuffs being added to the `bin/sparl-notebook` file
~~```~~
~~declare -r script_conf_file="/etc/default/spark-notebook"~~

~~declare -r app_classpath="/etc/hadoop/conf:$lib_dir/...~~

~~addJava "-Duser.dir=$(cd "${app_home}/.."; pwd -P)"~~
~~```~~

This might be integrated in the sbt build directly, so that this bin file can take more parameters specifying these values.

If not provided, we can fallback to env variables, if they do not exists that's fine because they are required for yarn _only_.

**EDIT**

This has been solved by introducing a new environment variable: `HADOOP_CONF_DIR` that will provide the information to the classpath.

**Comment by andypetrella** [comment]
AFAIU this would need a bit of improvement only regarding how the config are passed to the env.

Besides that, the documentation and the yarn profile are okay (am I right?)

So, maybe @virtualirfan and/or @minyk could you drop here what you discovered that needs to be improved?

Thanks a LoOot ^^.

**Comment by RPCMoritz** [comment]
Could you document these options? Especially script_conf_file is pretty obscure, and the value doesn't make much sense either, and differs from the current default value in the script, which doesn't help :(

**Comment by andypetrella** [comment]
@RPCMoritz these info were mainly for hacking the thing until a better integration was provided in https://github.com/andypetrella/spark-notebook/commit/0bd0980ce9d08e5c3654ea9408db861c775ae2a9. So only exporting the env var will do the trick since the classpath will be changed.

That's why it wasn't documented further I would say.

But if you do have question or problems with that I'll be glad to help, feel even free to create an issue describing what you've done so far (and tried) and the problems, so we can track it.

WDYT?

**Comment by RPCMoritz** [comment]
What needs to be fixed then is the README.md which isn't up to date with regard to this change - I'm not sure those three lines really warrant a new issue, but reworking the entire section to make it more accessible just might.

**Comment by andypetrella** [comment]
You're right, damned, didn't noticed this variable hasn't been commented in the README

**Comment by andypetrella** [comment]
the doc had been updated actually (for a while I think)... let's close this :smile:
