### ISSUE TITLE
adam usage

### ISSUE THREAD

**Issue by antonkulaga** [andypetrella/spark-notebook#14]
I see that you added info about configuration spark-notebook with different things. I think guide about configuration with ADAM will also be useful

**Comment by andypetrella** [comment]
Heya, forgot this ticket... but there are three examples, the third currently updated and cleaned but here they are:
* Convert ADAM.snb
* Read 1000Genomes dataset (chr-N).snb
* Clustering Genomics Data using Adam and MLLib.snb

a blog on that will come soon!
