### ISSUE TITLE
dark theme for UI

### ISSUE THREAD

**Issue by davidholiday** [andypetrella/spark-notebook#146]
creating a dark theme for the UI would make late-night hacking a lot more pleasant.

**Comment by andypetrella** [comment]
true, we would then start a css dance, but I think this should be manageable (most of the style is in style.css)

**Comment by projectvalis** [comment]
i know there are probably lots of other more pressing issues - I just wanted to add this to the 'nice to have' list :-)

**Comment by andypetrella** [comment]
Indeed, I agree that this skinable thingy would be great actually! And the dark theme is interesting, for instance I always use a dark theme in my sublime

**Comment by digital10111** [comment]
Are we there yet?

**Comment by vidma** [comment]
IMHO reliability and a single, but beautiful UI is of greater importance.
so let's better improve the default white style first.
