### ISSUE TITLE
Reintegrate aether for deps management in scala 2.11

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#150]
Last comment in #143 is showing that.
Actually the build doesn't pass because some deps aren't available for scala 2.11

So the easiest will be to have aether for 2.11 and sbt for 2.10 until some time is spent on the support of sbt in scala 2.11.

**Comment by andypetrella** [comment]
poke @d10genes
I've created a new release with this change, so you can use scala 2.11 but note what I've explain here regarding sbt / aether :-(.

Sorry for the wasted time!

**Comment by d10genes** [comment]
Whoops, I should've told you earlier, but 2.11 isn't that important for me. I was just thinking that the newest version would be recommended for someone starting out like me. Thank you so much for the fix anyways!

**Comment by andypetrella** [comment]
@d10genes :-D. No problem, I needed to fix it.
Scala 2.10 is the most used and 2.11 has a slow penetration rate :-/. There are a lot of reasons for that, but still few people are using scala 2.11.

**Comment by petervandenabeele** [comment]
@andypetrella Interesting statement about the slow adoption rate of 2.11 vs. 2.10. I do not easily find evidence or reasons for this, do you have pointers?

**Comment by andypetrella** [comment]
@petervandenabeele it'd take time to recap everything, because that's history mixed with feeling.
But in a nutshell:
* scala 2.8 was the first really interesting scala version, by that I mean easily usable, thanks to the introduction of collection api (the builder thingy by a. Moors)
* scala 2.9 was the one used by Play 2, hence it was the first scala version to be known by the crowd and use for more general purposes
* scala 2.10 adds some stuffs really valuable for people to use it: macro, string interpolation, actors are akka based. It's also the version (feeling) that has many applications running in production
* scala 2.11 is more like java 6, people weren't picking up java 6 from java 5 because the added value wasn't worth enough the work (tests, and so forth). Moreover, AFAICT, a lot of libraries aren't yet cross compiling which is a pain then.

These are only opinions on my own of course :-)

**Comment by petervandenabeele** [comment]
Thanks @andypetrella for this detailed reply (very interesting for me as coming new to the Scala community).
