### ISSUE TITLE
Running notebooks not shown

### ISSUE THREAD

**Issue by gauravkumar37** [andypetrella/spark-notebook#158]
Running notebooks are not shown in the `Running` tab.
Even after executing some code and I can see that the kernel is running fine.

**Comment by andypetrella** [comment]
Yep,  so far there is no exposed session, however they are avaliable in the session branch of even in the PR #148. If would like (it would be great), you can check it out and let me know if there is something more you'd like to add 

Cheers 
Andy

**Comment by andypetrella** [comment]
I finally merged the #148 PR, so the running notebooks are shown in the running tabs \o/
