### ISSUE TITLE
Issue in running notebook with nginx ssl

### ISSUE THREAD

**Issue by gurvindersingh** [andypetrella/spark-notebook#169]
When running notebook server with nginx proxying connection to notebook with ssl enabled. Kernel can not start, in notebook you keep seeing "waiting for kernel to start". In browser I see this error

```
SecurityError: The operation is insecure. ].join('')
 kernel.js (line 445)
```

Another small issue is the mathjax url is hardcoded with http, so it should also check if the request url is https or http and use the same protocol to fetch js file.

**Comment by andypetrella** [comment]
So now it will use `wss` rather than `ws` when secure connection is used. Also MathJax URL has been fixed for that (but I'd prefer to DL it... anyway).

However, the server has to start with **HTTPS** enabled in order to behave accordingly.
For this, play needs an extra parameter: https.port.

Hence, `./bin/spark-notebook -Dhttps.port=1443 -Dhttp.port=1080` will do the trick by running the unsecure site on `1080` and the secure one on `1443`.
This is also true when using `SBT` directly.

**Comment by gurvindersingh** [comment]
Still there are few issues with https support. First it should not require to have http port if https is given. You can specify both if you like but not a requirement. Another when running behined nginx proxy with ssl enabled, I get this error after using the current master.

can't establish a connection to the server at wss://localhost:9000/spark-notebook/ws/api/kernels/bac766a9-a539-4aca-b4bf-4b9ed56091c5/channels?session_id=F9C5C39C8F33413583F071980C57D09F.
].join('')

So I am repoening the issue for now.

**Comment by andypetrella** [comment]
I'll check for both ports open,  need to see if play supports that first  :) 

regarding the second error, could you provide me a smallish ngnix conf so that I can mimic your env exactly?

**Comment by gurvindersingh** [comment]
Here is the nginx conf

server {
  listen 443;
  ssl    on;
  # Cert info and other stuff
  # ....
  location /spark-notebook {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass https://localhost:9000;
  }
}

**Comment by andypetrella** [comment]
Thanks I'm going to try, but I see that you `proxy_pass` for `https` is still using `9000` is that correct?

Did you launched the server like so: `sbt -Dhttps.port=9000` ? (same using the binary)

**Comment by andypetrella** [comment]
@gurvindersingh I created this PR that tweaks a bit the url building for web sockets, if you have a chance to give a try that would be really kind :-D

https://github.com/andypetrella/spark-notebook/pull/173
