### ISSUE TITLE
Some doc about wisp usage

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#187]
This could either be in the README, but It'd be better to refer to a notebook showing how to do + one or two screenshots

**Comment by aglagla** [comment]
H Andy,

I was going to send you a question about wisp and thought I'd better check here first.
So indeed doc about wisp would be great, as the wisp examples are "raw", meaning: no labels, titles, etc.

Also, some chart types are commented :  regression
And some are missing : histogram

Is there a reason ?  As I'm doing some visuals I can help with this.

**Comment by andypetrella** [comment]
Hey Alexis (@aglagla),

There are no good reasons, only bad ones like time :-D.
The WISP deps is quite old as well, I think there are newer ones.

The integration of new viz might require a bit of refactoring of the integration (related to involved types) but not so hard I guess.

You'll be very welcome to any contribution related to documentation here, since I'm rarely using WISP, but generally I'm happy with default viz, or extended using DyiChart :-/.

I'll surely support you for any questions you'd have on that (of course).

**Comment by aglagla** [comment]
Hey Andy,

Yes, time is the scarce resource :-/
Anyway, will be looking into it soon, as I need good viz.  Will be testing
Bokeh and Dyichart as well.

Cheers,

Alexis

On 9 Jul 2015 14:13, "Andy Petrella" <notifications@github.com> wrote:
>
> Hey Alexis (@aglagla),
>
> There are no good reasons, only bad ones like time :-D.
> The WISP deps is quite old as well, I think there are newer ones.
>
> The integration of new viz might require a bit of refactoring of the
integration (related to involved types) but not so hard I guess.
>
> You'll be very welcome to any contribution related to documentation here,
since I'm rarely using WISP, but generally I'm happy with default viz, or
extended using DyiChart :-/.

**Comment by andypetrella** [comment]
@aglagla done in #268 doc is in the notebook → check boxplot and histogram for instance
