### ISSUE TITLE
"logo.png" missing / 404s?

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#188]
Just downloaded and ran [this build](http://spark-notebook.io/dl/tgz/0.5.0/2.10.4/1.3.1/2.5.0) and I see 404s trying to load a `logo.png` file:

![](https://s3.amazonaws.com/f.cl.ly/items/2b3A0K2R0U2M1t3W2K15/Screen%20Shot%202015-05-21%20at%2010.41.16%20AM.png)

![](https://s3.amazonaws.com/f.cl.ly/items/0R0N043O421U0Y150P1X/Screen%20Shot%202015-05-21%20at%2011.00.11%20AM.png)

**Comment by andypetrella** [comment]
done :-D
