### ISSUE TITLE
Support for Spark 1.4.0

### ISSUE THREAD

**Issue by EronWright** [andypetrella/spark-notebook#199]
Spark 1.4.0 is days away from being released.    Let's add minimal support as soon as possible.

Support for the new features of Spark 1.4 will be covered in separate issues.

**Comment by andypetrella** [comment]
hello @EronWright, I'm glad to tell you that is actually already available on `master` or `branch-0.6`;
You can clone the repo and do:
```
sbt -Dspark.version=1.4.0-rc4 run           #  or dist for a ZIP
```

In this case, it'll use the 1.4 spark kernel, but it'll require the 1.4.0-rc4 to be available... they are not, so you can `simply` test it yourself by building spark:
```shell
git@github.com:apache/spark.git
cd spark
git checkout v1.4.0-rc4
build/mvn clean install -Pyarn -DskipTests=true -Dmaven.test.skip=true
```

Of course you can use other published 1.4 version (like rc1) ^^

**Comment by EronWright** [comment]
Note that Spark 1.4.0RC4 has version "1.4.0".   I was therefore able to run with RC4 with:
```
sbt -Dspark.version=1.4.0 run           #  or dist for a ZIP
```

**Comment by andypetrella** [comment]
ooops my bad... yes... :-/

sorry about that, copy paste hell

**Comment by andypetrella** [comment]
@EronWright do you think we could close this one?
thanks :)

**Comment by EronWright** [comment]
Andy, since 1.4.0 release is imminent, would it help to keep this open until then?   Could a new release of Spark Notebook occur shortly thereafter?

**Comment by andypetrella** [comment]
@EronWright I created a version 0.5.1 available from the http://spark-notebook.io website. Which solves a crappy bug but also include 1.4.0 as the default version now. So I guess we can close it now, wdyt?
