### ISSUE TITLE
Support for Spark Packages

### ISSUE THREAD

**Issue by EronWright** [andypetrella/spark-notebook#201]
Spark 1.3/1.4's spark-submit tool now accepts a `--packages` argument.  The value is treated as a Maven coordinate, automatically downloading the corresponding JAR and it dependencies to the classpath.  

The tool uses a few repositories out-of-box , including local-maven-cache, local-ivy-cache, Maven Central, and a repository associated with spark-packages.org.   Users may also specify custom repositories.

My suggestion is that packages be supported in notebook metadata to be employed as appropriate on both the driver and executor classpath.   Ideally packages would be first-class in the notebook template UI.

The essential code is here: [spark/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala::resolveMavenCoordinates](https://github.com/apache/spark/blob/branch-1.4/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L914)

**Comment by maasg** [comment]
@EronWright how is that different from the current `:dp` support?

**Comment by andypetrella** [comment]
@EronWright thanks for the reference, very interesting I must say!
Also, @maasg is right, you can use 
* `:dp` to ask for libraries to be included in the
 * the notebook classpath
 * the spark.jars property (which will ship them to workers) 
* `remote-repo` to add more ivy or maven repos (including s3 ones, which spark-submit cannot do)
* `local-repo` to tell where you want your ivy repo to land → I generally point it to my `~/.ivy2` but you could also set A different one per notebook (to split the downloads or whatever)

All these contexts are also available in the notebook metadata (see [here](https://github.com/andypetrella/spark-notebook/#using-the-metadata)):
* `customDeps` 
* `customRepos` 
* `customLocalRepo` 

Would those thiniges fill your needs or do you have something else in mind?

**Comment by EronWright** [comment]
@andypetrella  awesome - seems the delta is very small.   At a high-level the goal is to claim support for Spark Packages.  The only apparent gap is inclusion of the Spark Packages repository in the default resolvers.   Then update the docs.

Some extra info:
[Website](http://spark-packages.org/)
[Announcing Spark Packages](https://databricks.com/blog/2014/12/22/announcing-spark-packages.html)
[Publishing Instructions](http://spark-packages.org/artifact-help)
[Sample](http://spark-packages.org/package/databricks/spark-avro)

**Comment by antonkulaga** [comment]
I think it is a good feature, because putting everything to assembly.jar is not pleasant.

**Comment by andypetrella** [comment]
@antonkulaga you're right and that's exactly the purpose of `:dp`, hence you don't have to create an assembly :-D

Here we are injecting the spark-packages maven repo by default in the list of repos, which makes a LOT of sense
