### ISSUE TITLE
New -> Text File fails

### ISSUE THREAD

**Issue by tfindlay-au** [andypetrella/spark-notebook#237]
When looking at the Dash screen, you can click the "New" box on the top right, then select "File".

This creates an empty text file, with no data. However Spark Notebook tries to open it as a Notebook which in turn fails.

Possibly disable option to create empty text file ?
![capture](https://cloud.githubusercontent.com/assets/9065936/8517088/082564cc-2400-11e5-8e42-78ca784c60e1.PNG)

**Comment by andypetrella** [comment]
agreed let's remove this item for now until some work can be done on it.
In the meantime, I'll update the code to give a name to new created folders...
