### ISSUE TITLE
Default Spark master URL

### ISSUE THREAD

**Issue by dvenza** [andypetrella/spark-notebook#238]
From what I understand you can define clusters in the appropriate configuration file, but you cannot define one of those clusters to be the "default" one, when a new notebook is opened or created.
You have to go explicitly in the "clusters" page to use one of those clusters.

I tried setting the spark.master option in the manager/notebooks/custom/sparkConf section of the application.conf file, but it does not work and seems to be ignored.

I found out about the MASTER environment variable, it works, but that way I cannot set other options, like the memory size, etc.

This could be a bug report:

- options in application.conf file are ignored

or a feature request:

- add a way to specify a cluster as the default one

Thank you for this amazing project.

**Comment by andypetrella** [comment]
Arf, the `application.conf` file should do the trick.

Did you used a distro or sbt?

If you used a distro, don't forget to include the `application.conf` file explicitly in an `application.ini` or simply:
```
./bin/spark-notebook -Dconfig.file=./conf/application.conf
``` 
Otherwise, it won't be used, and thus your conf won't be taken into account :-(

**Comment by dvenza** [comment]
I used a distro and I put the file in application.ini. Since you tell me it is the correct way to do it and that it should work I will try more carefully and report back.

Is this the correct configuration I should use? Perhaps last time I did something wrong.
```
  notebooks {
    ###
    # Default custom configuration for all notebooks
    #
    custom {
      sparkConf  = {
        spark.master: "spark://test-master-001:7077"
      }
    }
  }
```

**Comment by andypetrella** [comment]
okido, no problemo

yes you're right, this should do the trick (if it's under the manager key as well, but I assume it is).

If this doesn't work and the ini or -D has been used... it's probably a bug then :-(

**Comment by dvenza** [comment]
Ok it works, sorry for the noise.

Thanks!

**Comment by andypetrella** [comment]
oki cool :-D

no problemo
