### ISSUE TITLE
Broadcast variable got assigned a null value on yarn

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#256]
this is related to https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/Word2VecParam.java#L49

looks like https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/Word2VecParam.java#L49 is not broadcasted correctly and got a null value in https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/SentenceBatch.java#L50 hence we have an NPE in https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/SentenceBatch.java#L171

**Comment by andypetrella** [comment]
@jarutis could you please drop here the logs you have for this guy?
Particularly the sn-session log file

It might also be worthy to increase the level of logs to debug in the application.conf → set the `log.level` to debug under `kernel`

thanks!!

**Comment by jarutis** [comment]
I didn't use Kryo.

**Comment by jarutis** [comment]
Added the log [here](https://gist.github.com/jarutis/c82d32ce61917e199e41)

**Comment by andypetrella** [comment]
Thanks @jarutis !

First this `java.lang.ClassNotFoundException:org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter` might be interesting to look at too. Doesn't that mean that some jar are missing? From Yarn/Hadoop for instance.
It's something you can check in the spark-shell environment, then add the corresponding libs in either `HADOOP_CONF_DIR` or `EXTRA_CLASSPATH` if you use master.


Second, I might be wrong there are 359 jars that will need to be sent over the network to the executors, looking at them, there are probably too many of them. But also there are clashes.

* all the spark dependencies have been added, I might be wrong (maybe Yarn needs them there) but I think you can get rid of them. Safe goes for their transitive deps. You can do that in your `:dp` or `customDeps` conf.
* same goes for the hadoop deps
* there are two different version of scala in the jars: 2.10.4 and 2.11.6. I think 2.11.6 has been introduced with spark-csv. This is of course subject to problem :-D.

I see some broadcast here and there in the logs so this process seems to work, but of course it's not an argument for our problem. We need to investigate further.

And you're right, it looks like debug mode wasn't activated. When you changed the `application.conf` key `manager.kernel.log.level` to `debug` did you also provided the path to the binary?
Like 
```
./bin/spark-notebook -Dconfig.file=./conf/application.conf
```

Otherwise, the changes won't be applied since it'll take the shipped conf file.

**Comment by EronWright** [comment]
@andypetrella I think you mistook 'expTable' for 'table' in your examination.  The NPE relates to 'table', so we're not dealing with a broadcast variable.   I will close this issue in favor of deeplearning4j/deeplearning4j#425, re-opening this one later as need be.

**Comment by andypetrella** [comment]
thanks @EronWright , you're most probably right, since it was the first time I really looked into the dl4j code, I can't imagine I had an enough good overview to got it :-D.

Don't hesitate to reopen indeed!
