### ISSUE TITLE
`val data = 1 to 10000` renders Notebook unresponsive

### ISSUE THREAD

**Issue by petervandenabeele** [andypetrella/spark-notebook#279]
Naively typing in the very first command from the "itas workshop"
(http://stanford.edu/~rezab/sparkclass/slides/itas_workshop.pdf)
`val data = 1 to 10000`
leads to unresponsive script:
<img width="1296" alt="screen shot 2015-07-25 at 2 17 40 pm" src="https://cloud.githubusercontent.com/assets/55656/8889373/aea1fa40-32d8-11e5-82c9-0bea93269d4d.png">

Testing the same with `1 to 100`, `1 to 1000`, `1 to 2000` leads to increasingly longer wait times. 

If possible, I suggest that we do not only "show" the ellipsis (...) using CSS,  but also cut-off the number of data points sent in the html to some reasonable default max (e.g. 1,000 would have worked here).

**Comment by andypetrella** [comment]
indeed, that's something we're planning to do, that is only call the plots when it asked for.

The thing here is that it will create 4 plots with all points in them (the points are there in json to allow oflline showcases).

So for now, you can do
```scala
val data = 1 to 10000
()
```

In the next version (probably 0.7.0.), it won't be required, but to plot we'll need to call xxx
```scala
val data = 1 to 10000
xxx(data, maxPoints=100)
```
for instance

**Comment by andypetrella** [comment]
there wasn't an entry on this plot thingy, not there is #280
