### ISSUE TITLE
Clarify what "Repos" means in edit-cluster dialog

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#296]
![](http://cl.ly/image/1Y0v0O1y2F1r/Screen%20Shot%202015-08-17%20at%207.19.33%20PM.png)

It would be nice to:

1. Make it clear that these are Maven "Repos" that are being referred to.
2. Include [the list of default repos](https://github.com/andypetrella/spark-notebook/blob/7aa82157841e9c81d161be93b98d51c8f81d8733/README.md#add-remote-repositories), both local (`~/.m2`) and remote.

**Comment by andypetrella** [comment]
similar to #282
