### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by benqua** [andypetrella/spark-notebook#325]
In the [Geo Data](https://github.com/andypetrella/spark-notebook/blob/master/notebooks/viz/Geo%20Data%20%28Map%29.snb#L141) notebook, the evaluation of the Scala Map of line 141 fails because of the → instead of ->.

Am I missing something or is there an issue with the encoding?

Tested on Ubuntu + Firefox and Chrome.

**Comment by andypetrella** [comment]
Arf... indeed, encoding problem!

Probably a conversion to apply when the data comes in the server at save time!
 Thanks for reporting that!

**Comment by andypetrella** [comment]
I tested the PR, worked superb even after having changed my encoding to something weird
