### ISSUE TITLE
Windows and CustomJars: Invalid Escaping

### ISSUE THREAD

**Issue by cbvoxel** [andypetrella/spark-notebook#326]
Hey @andypetrella ,
just worked on some stuff and needed the spark-csv library, so I used the great :dp functionality on windows (naturally ^^), which worked fine until the very end when the ReplCalculator had to integrate the custom jars (via the CustomJars variable). One thing sure to fail are Windows \ (backshlash) as scala interprets this as an escaping character... sooooo once again, a windows fail.

There is one small change needed (ReplCalculator): .replace("\\","\\\\") 

I will see if I can manage another PR for this, okay? Or do you have any other ideas?

**Comment by andypetrella** [comment]
Ohhh damned, indeed...

So better use [pathSeparator](http://docs.oracle.com/javase/7/docs/api/java/io/File.html#pathSeparator) instead?

WDYT?

**Comment by cbvoxel** [comment]
I don't thinks that's the problem here - this is the error message:

2015-09-23 20:00:29,918 ERROR [Remote-akka.actor.default-dispatcher-3] (notebook.client.ReplCalculator) - Error in init script: 
<console>:2: error: invalid escape character
       val CustomJars = Array("C:\Users\Carsten\AppData\Local\Temp\spark-notebook\repo\f6eec9e4-0ed7-4b5d-92cf-40392b85b183\cache\com.databricks\spark-csv_2.10\jars\spark-csv_2.10-1.2.0.jar","C:\Users\Carsten\.m2\repository\org\scala-lang\scala-library\2.10.4\scala-library-2.10.4.jar","C:\Users\Carsten\AppData\Local\Temp\spark-notebook\repo\f6eec9e4-0ed7-4b5d-92cf-40392b85b183\cache\org.apache.commons\commons-csv\jars\commons-csv-1.1.jar","C:\Users\Carsten\AppData\Local\Temp\spark-notebook\repo\f6eec9e4-0ed7-4b5d-92cf-40392b85b183\cache\com.univocity\univocity-parsers\jars\univocity-parsers-1.5.1.jar")

Which points the problem towards the '\' sign. I thought about an elegant way, but the truth is, that my suggestion is most likely and unfortunatly the best way to deal with this. Yes it seems like a dirty fix, but it isn't. You are generating code here and only here it is important to know that a \ character within your data (deps) will cause trouble. Even if you use triple double quotes (yikes what a combo!) you stumble over \un with seems to be a unicode escaping character - wierd. This isn't only a windows phenomena, though it is absolutely inavoidable, but it may happen for situations where you have real \ in a linux path - okay that's quite unlikely, but still, it should be handled.

**Comment by andypetrella** [comment]
isn't this on fixed too ^^?

**Comment by cbvoxel** [comment]
Yep, I think so. It hasn't shown up since! 
I'll close this, okay? 

Cya and Cheers!
