### ISSUE TITLE
Proxy config not supported under scala 2.10

### ISSUE THREAD

**Issue by huitseeker** [andypetrella/spark-notebook#341]
In https://github.com/andypetrella/spark-notebook/blob/master/modules/common/src/main/scala-2.10/notebook/util/Deps.scala#L124 :
` // TODO :proxy: val proxy = Try(config.getConfig("proxy")).toOption` 
(there's a bit more too that, see https://github.com/andypetrella/spark-notebook/blob/master/modules/common/src/main/scala-2.11/notebook/util/Deps.scala#L53 )

**Comment by RPCMoritz** [comment]
Re proxy config, there's this an already, which you may want to amed: https://github.com/andypetrella/spark-notebook/issues/184

**Comment by andypetrella** [comment]
Thanks to highlight that one! I think that I didn't managed yet to find how these configuration shouldn't be applied to `MavenRepository` or `Resolver`.
Actually I thought they would be auto-magically taken into account by sbt under the hood by just dropping them in the default configuration. But I think it's not that easy ....

@huitseeker do you have any insight about that?

**Comment by huitseeker** [comment]
@andypetrella Any further isolation for this one ?

**Comment by andypetrella** [comment]
Not yet, I'll take a look asap (I'm overwhelmed with Devoxx preps atm -_-)

**Comment by andypetrella** [comment]
Wait, I think I got it!
I guess those guyz need to be set as Java Props!!!
I'll update the code and maybe you @huitseeker or @RPCMoritz can give it a quick try?

**Comment by huitseeker** [comment]
This looks good to me ! The resolution issues:
![notebook1-c](https://cloud.githubusercontent.com/assets/4142/11022819/0352da3a-8669-11e5-9924-e2c2feb3d40f.png)
completely disappear:
![notebook2-c](https://cloud.githubusercontent.com/assets/4142/11022822/1471b304-8669-11e5-9ca1-a9a3ca55e460.png)

**Comment by huitseeker** [comment]
https://github.com/andypetrella/spark-notebook/pull/370 << looks good :+1:

**Comment by andypetrella** [comment]
\o/ wooohooooo :-)
