### ISSUE TITLE
Unicode characters in notebooks not loaded correctly into the editor

### ISSUE THREAD

**Issue by radekg** [andypetrella/spark-notebook#345]
Hi @andypetrella,

An issue is the following: when running the notebook inside of the docker container, the UTF-8 characters are malformed when opening the notebook in the editor. Looking at `viz/Graph Plots.snb` for example:

![image](https://cloud.githubusercontent.com/assets/62946/10526766/03c603d2-738d-11e5-8236-cbcce717d1b9.png)

I believe the issue is that the `snb` file is not explicitly read as unicode, neither the JSON response is explicitly setting `Content-Encoding` in the `getNotebook` response. Any chance to look at this issue?

**Comment by andypetrella** [comment]
fixed by https://github.com/andypetrella/spark-notebook/commit/af3e84b071d6c3056fef2ae00aa9b4f5cf91c4a5 thanks to @radekg !!!

**Comment by radekg** [comment]
:+1:
