### ISSUE TITLE
No way to navigate to other cells when using magic plot 

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#356]
loading vis/Magic Plot, as well as trying plots in other notebooks, when i try to place the cursor in another cell, the browser jumps to the chart

**Comment by andypetrella** [comment]
dude! Really?
Which browser are you using, Chrome too?

I never heard about that before, really strange :-S

**Comment by ittayd** [comment]
Yes, Chrome.

**Comment by andypetrella** [comment]
c'mon
would you mind screencasting this? it'll help me understand what the heck is going on...

**Comment by ittayd** [comment]
ok, what tool do you recommend?

**Comment by andypetrella** [comment]
I guess you could use something like camstudio (I don't know it, since I don't have any windows around, as you have noticed :-( )

**Comment by ittayd** [comment]
http://youtu.be/iX5X_TroHfQ?hd=1

(i'll delete the video in about a day or so, if you don't mind)

**Comment by ittayd** [comment]
I tried to dig into this. The chart is surrounded by a div that looks like ```<div class="tab-pane active" id="tab1922992278-1">```. If I remove the 'active' class, then the chart collapses to just the table/bar/pie icons and the weird behavior is gone. 

If this still doesn't help to find the bug, maybe add a way (button) to collapse charts, so I can at least collapse them and continue working? I can collapse the entire output, but that is cumbersome and sometimes I want the output there as it contains other information.

**Comment by ittayd** [comment]
Further digging shows that if I add the class to another chart manually, then the chart opens, but the scrolling effect doesn't happen. This suggests is it not related to some CSS issue. The event handlers for the bar chart icon's click are:
![image](https://cloud.githubusercontent.com/assets/33328/10714321/d12d8cc4-7af3-11e5-9993-07d824e6c4bb.png)
I tried looking into what the event handler for 'a' is, but this just opens a blank page.

**Comment by ittayd** [comment]
This scriplet works around the issue: javascript:$('.tab-pane').removeClass('active')

Because it removes a class, I think the issue is with CSS or Chrome's rendering.

**Comment by andypetrella** [comment]
Mmmmh, so are you thinking that chrome's renderer with this active tries to allways focus on the chart for all further clicks?

It's weird I don't have this problem on my chrome though, maybe mine is older than yours. What's your version?

**Comment by ittayd** [comment]
Actually, after thinking more about it, maube there is a global click event that then targets $('.active')

**Comment by andypetrella** [comment]
indeed, you're right that it might be the case, but why I don't have this pbm too :-(

**Comment by ittayd** [comment]
my chrome version is  46.0.2490.71 m. 

I tried running chrome in incognito, same behavior. Maybe something else is overlaying the display settings or something?

**Comment by andypetrella** [comment]
I'm Version 45.0.2454.101 (64-bit) a bit older and linux.
What's weird is that this active thingy is from bootstrap oO

**Comment by ittayd** [comment]
It's not from bootstrap. Check tabs.coffee under the magic javascript folder

**Comment by ittayd** [comment]
OK, so I cloned the repository and now I can see all code ;-). And yes, it looks like bootstrap.js relies on the 'active' class fro its ScrollSpy plugin. And according to its name, it may be the culprit... I'll try changing tabs.coffee to use a different class and report back

**Comment by ittayd** [comment]
Yes, it is from bootstrap. Can't say why it doesn't work.

**Comment by ittayd** [comment]
Looking at the description for tabs in Bootstrap, some things don't match in the magic plot implementation. There's no 'role' attribute, tabs are shown by toggling the class (in tabs.coffee) instead of tab('show'). Maybe this causes the issues?

**Comment by andypetrella** [comment]
@ittayd just did some adaptations in there, would be lovely if you can give it a shoot :-D

**Comment by ittayd** [comment]
works!
