### ISSUE TITLE
magic plot doesn't show histogram according to printed order

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#357]
```res24: Array[(Char, Int)] = Array((a,1561), (b,1099), (c,1897), (d,999), (e,1011), (f,933), (g,592), (h,785), (i,661), (j,270))```

But in the histogram the order is c, a, b, e, d, f, h, i, g, j

**Comment by andypetrella** [comment]
Indeed, I saw that one too, will be fixed in master and for 0.6.2!
The stuffs are reorganized based on the values (I think this is a dimplejs thingy...)

**Comment by andypetrella** [comment]
ooops I already fixed that in a previous commit, forgot to mention the issue :-D.
So on master → fixed
