### ISSUE TITLE
'Using DataTable' notebook has errors

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#358]
```
In [7]:

import notebook.Codec
import notebook.JsonCodec._
​
implicit val dataCodec:Codec[JsValue, Data] = formatToCodec(f)
<console>:56: error: type mismatch;
 found   : play.api.libs.json.Format[Data]
 required: Option[String => Data]
       implicit val dataCodec:Codec[JsValue, Data] = formatToCodec(f)
```

**Comment by andypetrella** [comment]
Yep, this data table thingy is gonna be deprecated soon... in favor of the table shown for DataFrame

although, I'll check it out for sanity and completeness

**Comment by ittayd** [comment]
I hope all the issues I'm opening do not make it look like the project is bad. It is actually one of the more amazing tools I have used. Excellent work and thank you!

**Comment by andypetrella** [comment]
no worries dude! keep on the great work!

it's funny because I just commented that on the later issue I reacted on :-D.

And, of course, thanks A LOOOOT for the kind words :-P, very appreciated
