### ISSUE TITLE
question: is there a way to securely connect to a production cluster? 

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#360]
This means specifying credentials or whatever is customary (we don't have a production cluster yet) when connecting and also maybe protecting the notebook so it doesn't accept connections from other machines.

**Comment by andypetrella** [comment]
not yet, this is of course some work we'll do soon or sooner but requires some more stuff to work properly  in a full secured context (think about it, the notebook provides access to the whole machine via the embed repl ^^).

However, to use secured cluster, we use SSH tunnel and we start the spark notebook on the distant machine.
