### ISSUE TITLE
SparkInfo widget doesn't work

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#361]
```
In [8]:

import org.apache.spark.ui.notebook.front.widgets.SparkInfo
import scala.concurrent.duration._
new SparkInfo(sparkContext, checkInterval=1 second, execNumber=Some(100))
warning: there was one feature warning; re-run with -feature for details
import org.apache.spark.ui.notebook.front.widgets.SparkInfo
import scala.concurrent.duration._
res5: org.apache.spark.ui.notebook.front.widgets.SparkInfo = <SparkInfo widget>
Out[8]:
687 milliseconds
```

Nothing is shown besides that, even if I execute some RDDs

Not sure if related, but in the Javascript console I see:
```
mimebundle missing metadata Object {output_type: "execute_result", data: Object, metadata: undefined, execution_count: 9, time: "541 milliseconds"}data: Objectexecution_count: 9metadata: Objectoutput_type: "execute_result"time: "541 milliseconds"__proto__: Object
:9000/assets/javascripts/notebook/observable.js:112 Creating new observable (client request): anon21fd04d574c13004c8cab672f47a050e
```

**Comment by andypetrella** [comment]
Right, this widget is very lightweight (although interesting), but still need a bit of revamping to make it work with later spark version

**Comment by andypetrella** [comment]
I'm going to deprecate the spark info btw, so I'll close it when it'll be removed :-D

**Comment by ittayd** [comment]
Will there be an alternative? It is a good way to demonstrate without jumping to other pages

**Comment by andypetrella** [comment]
Yeah, sure!

Actually now there are visual enabled per default. Right now they are pie chart showing the tasks. But it is subject/open to changes and enhancement :-D

**Comment by andypetrella** [comment]
this one is deprecated since now this information is available in progress bar, which is still under dev but at least works :-) #311
