### ISSUE TITLE
dataframes with Vectors cause mimebundle missing metadata exceptions

### ISSUE THREAD

**Issue by alpinegizmo** [andypetrella/spark-notebook#365]
The machine learning libraries in Spark ML expect to work on dataframes that contain Vectors, but these seem to make spark notebook unhappy. It is possible to go ahead and fit models, etc, but we want to use this environment for training, so we hope to find a workaround or a fix for this.

    val sqlContext = new org.apache.spark.sql.SQLContext(sc)
    import sqlContext.implicits._
    
    import org.apache.spark.mllib.regression.LabeledPoint
    import org.apache.spark.mllib.linalg.{Vector, Vectors}
    
    val data = sc.parallelize(Seq(
        LabeledPoint(0, Vectors.dense(0, 2, 3)),
        LabeledPoint(1, Vectors.dense(0, 3, 1)),
        LabeledPoint(0, Vectors.dense(0, 2, 2)),
        LabeledPoint(1, Vectors.dense(0, 3, 9)),
        LabeledPoint(0, Vectors.dense(0, 2, 6))
    ))

    val df = data.toDF

![screenshot 2015-10-27 at 16 54 37](https://cloud.githubusercontent.com/assets/43608/10763745/71d5d432-7ccb-11e5-9ac1-c0584365fdae.png)

**Comment by andypetrella** [comment]
@alpinegizmo indeed, you're right. However, it works on the current master (soon to be released as 0.6.2). It's not perfect because cannot render well the embed objects → working on it...

**Comment by andypetrella** [comment]
BTW, now embed objects are supported :-D

**Comment by alpinegizmo** [comment]
Thanks! I updated to running master and it works fine.
