### ISSUE TITLE
Table preview of SchemaDD / DataFrame

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#37]
Show the rows in the RDD in a table.

Even cooler would be to have a R's `summary` functionality on it.

**Comment by axlpado** [comment]
is this covered by #125 ? or are  you thinking something different ?

**Comment by andypetrella** [comment]
I guess so, since `SchemaRDD` doesn't provide much interesting insight into the underlying data type...

Maybe, extending https://github.com/andypetrella/spark-notebook/pull/125 in order to deal with `RDD` or only `SchemaRDD`. So we could have, for instance a tab with the `toDebugString`, the `EXPLAIN` and what not.

Wdyt?

(In htis case, I'd rename this entry to to rescope to what's being proposed)

**Comment by axlpado** [comment]
yes, the concern is that you have something printable when you perform an action over the RDD.

maybe we can check where RDD is trasformed in a Seq and forward debug info to the renderers.
I'll try to investigate it

**Comment by andypetrella** [comment]
Exactly, maybe shall we consider having something using `takeSample`. With a input box allowing user to specify his preferences in size (with `0` being the default maybe).

Also, regarding SchemaRDD, the DataFrame API can be really interesting is this case: see slides 17 and 18 in http://www.slideshare.net/databricks/introducing-dataframes-in-spark-for-large-scale-data-science (the display stuffs and so on are coming from the the databricks cloud product, though).

So this looks giving more control on the structure

**Comment by axlpado** [comment]
Yes, I saw that slides this morning ! :-) nice API

anyway also the dataframe needs a command to collect data, in that case it's hidden by display().

We can consider a display command that wrap the collect one or the takeSample one. Once we collect data table is already available

**Comment by andypetrella** [comment]
agreed, automatic plotting will be harder
* need an action, that might be consuming hence not wanted all the time
* more data, hence what is the best sample? take, takeSample?

Having a display function that would choose the tabs like now for regular collections would be really good.

Also, having a small form that would let the user choose the two(?) fields to be used in the display would be nice. So on top on the tabs (that in case of more than 2 fields) we could have two drop down lists. Changing them will adapt the tabs :-D
→ WDYT, does it make sense? Should we create another issue/feature request for this?

**Comment by axlpado** [comment]
Yes,

I would avoid automatic action over rdd because it will recalculate all the pipeline in each step. We could think about that over CachedRDD...

Choosing fields from a table to enable chart tabs could be very interesting! Let's create the feature and I will check how to build it.

Paolo

**Comment by andypetrella** [comment]
Ineed that would be awesome!!

**Comment by andypetrella** [comment]
now a duplicate of #200 which is almost there
