### ISSUE TITLE
docker image pull not working

### ISSUE THREAD

**Issue by geoHeil** [andypetrella/spark-notebook#371]
Hi,
I try to docker pull using

```
docker pull andypetrella/spark-notebook:master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1
```
but apparently this is not possible.
```
docker run -p 9000:9000 andypetrella/spark-notebook:master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1
Pulling repository docker.io/andypetrella/spark-notebook
Tag master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1 not found in repository docker.io/andypetrella/spark-notebook
bash-3.2$ docker run -p 9000:9000 andypetrella/spark-notebook:master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1
Unable to find image 'andypetrella/spark-notebook:master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1' locally
Pulling repository docker.io/andypetrella/spark-notebook
Tag master-scala-2.11.6-spark-1.5.1-hadoop-2.7.1 not found in repository docker.io/andypetrella/spark-notebook
```
What is wrong?

**Comment by andypetrella** [comment]
damn the message is deprecated: 
```
docker pull andypetrella/spark-notebook:0.6.2-SNAPSHOT-scala-2.10.4-spark-1.5.1-hadoop-2.7.1	
```

sry

**Comment by geoHeil** [comment]
Thank you very much. This works!

**Comment by geoHeil** [comment]
However now I get: 

''''
docker pull andypetrella/spark-notebook:0.6.2-SNAPSHOT-scala-2.10.4-spark-1.5.1-hadoop-2.7.1
Pulling repository docker.io/andypetrella/spark-notebook
Error while pulling image: Get https://index.docker.io/v1/repositories/andypetrella/spark-notebook/images: dial tcp: lookup index.docker.io on 130.236.48.2:53: server misbehaving'''

**Comment by andypetrella** [comment]
argl, looks like it's on your side. Apparently a problem with DNS and boot2docker (sorry not mac user):
http://stackoverflow.com/questions/28301151/docker-pull-error

could you try that (restarting the VM)?

**Comment by geoHeil** [comment]
Thank you!
