### ISSUE TITLE
MapR distribution

### ISSUE THREAD

**Issue by rickyking** [andypetrella/spark-notebook#383]
I have problem while compiling the source code for MapR:

```
[error] (subprocess/*:update) sbt.ResolveException: unresolved dependency: org.apache.hadoop#hadoop-client;2.7.0-mapr-1506: not found
[error] unresolved dependency: org.apache.hadoop#hadoop-yarn-server-web-proxy;2.7.0-mapr-1506: not found
```

While issuing the following command `sbt -Dspark.version=1.4.1 -Dhadoop.version=2.7.0-mapr-1506 -Dwith.hive=true -Dwith.parquet=true clean dist` as instructed in README.md

**Comment by andypetrella** [comment]
Hello @rickyking , I guess that we need to add another repo for MapR?

What about this one http://repository.mapr.com/nexus/content/repositories/releases/ 
(or simply http://repository.mapr.com/maven/) ? 

We could try adding this to the list here: https://github.com/andypetrella/spark-notebook/blob/master/build.sbt#L56.

It looks like it contains at least the distribution you were requested, including the specific package that the notebook failed to resolve: http://repository.mapr.com/nexus/content/repositories/releases/org/apache/hadoop/hadoop-yarn-server-web-proxy/2.7.0-mapr-1506/.

Would you give that a quick try? That would be awesome :-).

**Comment by rickyking** [comment]
Thanks!! 
It works!

```
[repositories]
        local
        mapr: http://repository.mapr.com/maven
```

**Comment by andypetrella** [comment]
super cool, so we can add this repo to the list I guess...
wdyt @rickyking ?

**Comment by rickyking** [comment]
Yes we can!
