### ISSUE TITLE
Toggle of cell output using shortcut keys does not reflect menu cell output toggle

### ISSUE THREAD

**Issue by jp-gorman** [andypetrella/spark-notebook#387]
Run some cell entries that output numbers 1-10
select some graph for the numbers to have graphical output
select the cell and then escpe out of edit mode but still on cell
select t/o for toggle output on / off as per help on keyboard shortcut
Expected: Toggle of the output
Actual: The output only partially is cleared. Graph and some output not clered.

Note:
Repeat the same steps above but toggle the output from the menu (Toggle Current output)
The menu toggle applies an elipse "..." to toggled sections, keyboard shortcuts do not.

To Fix: Allow keyboard to do the same as the menu options as that seems to work

Version: andypetrella/spark-notebook:0.6.2-SNAPSHOT-scala-2.11.6-spark-1.5.1-hadoop-2.2.0-with-parquet 

I checked for toggle/output in existing defects and did not find - excuse me if its a dupe or fixed already.

**Comment by jp-gorman** [comment]
p.s. I don't seem to be able to clear the worker graphs "collect at <console>:44" when they get stuck on screen (completed/pending) - They don't clear upon full output clear (I can imagine they were never tied into this, but just wondered if there is a way to hide them? Interesting thing happens on cache clear and hard reset in Chrome, I get multiple pie charts down the left hand side, even though the actual subsequent collect refreshes to display only 1 chart (and clear all the odd additional ones)

val nums = sc.parallelize(List(1, 2, 3, 4, 5, 6, 4))
nums.collect

**Comment by andypetrella** [comment]
okay, so you mean that hiding the output with `o` doesn't work? Because there is no clear shortcut I mean.

The pie on the left are indeed persitent (cannot be cleared) → this should be possible, could you put that in a issue to track that down and solve it?

These pies will be replaced by a dedicated widget/panel in the next version though

**Comment by jp-gorman** [comment]
Andy,

I tried this again now and the "o" key work to bring about the toggling of the output and the elipse "...". The "t" toggle appears t toggle the output type generated. Given that, a small change to the keyboard shortcut explanation is all that is needed sometime if at all.

If the worker graphs are being replaced, then I would not bother swapping out, as they are just a quick indication and full details are on the spark UI if needed - Perhaps just close this off with a link to the new feature as "won't fix")
