### ISSUE TITLE
Progress pie charts do a weird "time warp" when loading a notebook that's been running for a while

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#398]
Just opened this notebook in my browser that was running for several hours without me having an active browser tab session watching it, and I see this:

![](http://f.cl.ly/items/2A1L3K2r2541222t0T0z/Screen%20Recording%202015-11-27%20at%2010.51%20AM.gif)

It's fast-forwarding through a bunch of jobs/stages that I missed, but not in a way that seems intentional/useful.

I've seen this twice in similar circumstances.

**Comment by vidma** [comment]
not 100% sure what it means. but have in mind this sums up the progresses of multiple stages of the same name, so progress can go up and down any time.

I have a PR with slightly improved presentation in #395 (where stages would be shown separately).

and we're about to take on a great rework which will allow to associate progresses to the cells themselves in #311 .

**Comment by vidma** [comment]
#395 solves this.
