### ISSUE TITLE
No java installations was detected error

### ISSUE THREAD

**Issue by donigian** [andypetrella/spark-notebook#409]
Steps to reproduce: Install spark-notebook using DCOS (mesosphere) but the app deployment failed on slave sandbox due to `No java installations was detected`. This is likely due to the `$JAVA_HOME` variable not being set properly.

**Comment by donigian** [comment]
The fix is to update the marathon.json [https://github.com/mesosphere/multiverse/blob/5ffa5189bc2daf9abd63e0874d9aed5794c4f407/repo/packages/S/spark-notebook/0/marathon.json#L6] file for spark-notebook in Multiverse by adding and prefixing `export` as below:
```
"cmd": "export JAVA_HOME=$(pwd)/jre1.7.0_76 && cd spark-notebook-0.6.0-scala-2.10.4-spark-1.4.0-hadoop-2.4.0 && ./bin/spark-notebook -v -Dmanager.tachyon.enabled=false -Dhttp.port=8899 -J-Xms4000m -J-Xmx4000m -Dmanager.notebooks.custom.sparkConf.spark.mesos.executor.docker.image=\"mesosphere/spark:1.4.0-rc4-hdfs\" -Dmanager.notebooks.custom.sparkConf.spark.master=\"mesos://zk://master.mesos:2181\" -Dmanager.notebooks.custom.sparkConf.spark.mesos.executor.home=\"/opt/spark/dist\"",
```

**Comment by andypetrella** [comment]
yes thanks!
We also XP some problems when accessing it using the DCOS dns, we only were able to access the spark notebook using the ec2 dns is that still the case?
