### ISSUE TITLE
get rid of maxPoints widget altogether

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#422]
after some though we concluded it best to get rid of maxPoints selection widget altogether - it's clutters the UI too much, and people can always limit the number of rows to display manually (with `.limit` or `.take`). 

- [x] remove maxPoints widget  from everywhere #585
- [ ] the default 1000 limit could stay, need to think how persist to the warning that only subset of datapoints are show
@andypetrella

**Comment by andypetrella** [comment]
indeed, I had the same thought recently about the badly chosen name.
I'd go for either `maxEntries` or maybe `maxObservations`? Maybe `maxEntries` is more generic.

Oh and definitely, let's save the max in the output.

This capability to save information back to the saved output is more and more needed (for #416 too), we'll probably have to mutualize this work in a easily accessible function or whatever -- like a function that would take a function going giving outpus as parameter and must return the new output (here output is the text in the json doc)

**Comment by vidma** [comment]
after some thought, decided to remove maxPoints, updated description.
@andypetrella 

I could look into this on Friday maybe (or feel free to do this yourself!).
