### ISSUE TITLE
SparkUI link occasionally links to localhost instead of the correct IP

### ISSUE THREAD

**Issue by shadjiiski** [andypetrella/spark-notebook#425]
I am running the notebook and using it on two distinct machines. I have noticed that occasionally SparkUI link gets mapped to localhost instead of the correct IP address. Judging by the Spark UI port number, the external IP discovery fails only on the first spark context initialization (i.e. there were no running kernels before). However, on attempts to reproduce this bug the link completely disappeared. So did the progressbars. I will update the issue if I get more info on this.

I am using a master build:
Build: |  buildTime-Mon Dec 07 14:34:13 EET 2015 | formattedShaVersion-0.6.2-SNAPSHOT-965aa22546c3514f9b5b5982d270c075f9c88c49 | sbtVersion-0.13.8 | scalaVersion-2.10.6 | sparkNotebookVersion-0.6.2-SNAPSHOT | hadoopVersion-2.6.0-cdh5.4.2 | jets3tVersion-0.7.1 | jlineDef-(org.scala-lang,2.10.6) | sparkVersion-1.6.0 | withHive-true | withParquet-true |.

**Comment by vidma** [comment]
use `SPARK_PUBLIC_DNS=whatever-public-host-where-spark-notebook-runs`. see #399
