### ISSUE TITLE
[BLOCKER] Notebook not responding sometimes

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#429]
- [x] handle cases of kernel failure (e.g. outofmemory in physical machine)
- [x] maybe reduce mem usage: start kernel lazily. makes sense for `*example*` notebooks #436 

* no 100% sure of the real cause yet, but looks like `OutOfMemory` and related issues forcing `kernel` to die
* with larger number of users we observe from time to time the notebook to behave very weirdly, which manifests by one or more of these:
  - loading any notebook page (index for example) taking/blocking very long
  - unable to run a cell / cell run do not complete - no log/debug messages from kernel visible in browser console
* in most cases kernel shutdown and restart fixes the matters, but it's horribly annoying
  - progressbar invisible
  - sparkUI link visible, no progressbar

a few thoughts:
- maybe because we have larger number of users and multiple notebooks being used (~8 users, ~4-10+ notebooks open simultaneously)
- maybe running out of memory on machine or in kernel process
  * a few more interesting exceptions (`Native memory allocation (malloc) failed to allocate 470.286.336 bytes for committing reserved memory.`; `Process exited with an error: 137` ) I've seen (not yet sure if they correlate with the issue yet):
https://gist.github.com/vidma/ad365d9317fb50d888e7
- maybe related to same notebook file being open simultaneously in multiple browser tabs (or on multiple computers)
- more ideas ???

@andypetrella

**Comment by andypetrella** [comment]
this is indeed rather painful, let's shoot this one and give it the highest priority!

One potential problem that we need to track would be the amount of web socket opened and registered to the notebooks: https://github.com/andypetrella/spark-notebook/blob/acfdbf5742d8b84d02cd11541a1c2d6388dff6fc/app/notebook/server/CalcWebSocketService.scala#L105. It might be a long operation if there are many running requests/events/messages → which are including logging events!
For this let's first track the time (maybe between a register request and the time it has been actually registered to the listeners list, this might help...

The other is indeed, having many notebooks opened on the same machine, which have their own heap might be a problem → this has to be solve by allowing the server to use a cluster manager like mesos to spawn notebooks elsewhere (or allowing notebooks to explicitly using the same kernel/sparkContext (see #277) 

These my first ideas on this, pass me the word, _crap_.

**Comment by vidma** [comment]
so the first issue looks just like the machine went out of available memory, process dump:
```
ParallelGCFailedAllocation ...
Memory: 4k page, physical 32g (344m free), swap 1g(0k free) 
tried to allocate 470mb
```
