### ISSUE TITLE
Rendering GeoJSON containing "bbox" elements throws exceptions

### ISSUE THREAD

**Issue by jp-gorman** [andypetrella/spark-notebook#433]
Add the below GeoJSON example code, and try and render in the GeoChart using:

Expected: GeoJSON rendered
Actual: Exception occurs in rendering (Andy - had quick review and it looks like the library is not handling "bbox" elements)

https://github.com/bjornharrtell/jts2geojson/tree/master/src/main/java/org/wololo/geojson

Start Example
-------------------------
(Step 1. Define GeoJSON setup)

val geoJSON = """
{
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "id": 1,
        "geometry": {
            "type": "Point",
            "coordinates": [-8.311419016226296, 53.894485921596285],
            "bbox": [-8.311419016226296, 53.894485921596285, -8.311419016226296, 53.894485921596285]
        },
        "properties": {
            "FID": 335,
            "PLAN_REF": "151",
            "APP_TYPE": "RETENTION",
            "LOCATION": "Knockglass, Ballinameen, Co. Roscommon.",
            "REC_DATE": "05/01/2015",
            "DESCRIPT": "Of entrance to existing forest plantation for extraction of timber at various times at                                                                                                                                                                        ",
            "APPSTATUS": "Application Finalised",
            "DEC_DATE": "20/02/2015",
            "DECISION": "Granted (Conditional)",
            "APPE_DEC": "n/a",
            "APPE_DAT": "n/a",
            "MOREINFO": "http://www.eplanning.ie/roscommoneplan/FileRefDetails.aspx?file_number=151",
            "WGS_LONG": "-8.31141",
            "WGS_LAT": "53.89448"
        }
    }]
}
"""

(Step 2. Parse the GeoJSON)

val geoJSONRepr = GeoChart.parseGeoJSON(geoJSON)

**Comment by andypetrella** [comment]
@jp-gorman I updated the libs, waiting for @bjornharrtell review now :-)

**Comment by jp-gorman** [comment]
Yeah - I just saw him merge your PR and had a look at ho it was implemented. Good stuff, I'll pull once you merge into master.

**Comment by bjornharrtell** [comment]
Happy to see my little lib put to good use so I tagged 0.7.0 and published to maven central, will be available there tomorrow.
