### ISSUE TITLE
kill notebook after idle time

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#446]
- [x] add config param to turn on, and set idle time
- [x] kill `calculator` jvm, after idle time, say 60 minutes
  * idle time means: no cell were executing for given amount of time
  * we don't care about `Futures` in cells

@andypetrella  shouldn't be too hard to implement I guess ;)

**Comment by andypetrella** [comment]
If it's a parameter in the notebook → :+1: 

We'll have to take care of the long running cells, indeply of the future ones. 60 minutes without running cells and no cell is currently running...

**Comment by vidma** [comment]
fixed in #526
