### ISSUE TITLE
Support tab completion

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#499]
Seems like IPython notebook supports tab completion, would be great to support it in scala-notebook. Even greater if links to documentation can be shown

**Comment by vidma** [comment]
there is one! just press tab, once the kernel is ready (spark-context is loaded).
see https://github.com/andypetrella/spark-notebook/pull/466 and https://github.com/andypetrella/spark-notebook/pull/453

> Even greater if links to documentation can be shown

what do you mean?

#471

**Comment by ittayd** [comment]
How exactly does this work? I downloaded a fresh build (from master) and in
a cell I type `"sss".` (without the backquotes), hit <tab> and nothing
happens

**Comment by ittayd** [comment]
sorry, it just took several seconds to happen....
