### ISSUE TITLE
Spark 1.6 support

### ISSUE THREAD

**Issue by alpinegizmo** [andypetrella/spark-notebook#506]
Very eager to see this, especially via spark-notebook.io. We are introducing dependencies on Spark 1.6 into our future training sessions.

**Comment by vidma** [comment]
should work out of the box though, just compile for spark `1.6.0`.

I think spark-notebook.io also works with 1.6.0 (one can enter a custom version!)

**Comment by andypetrella** [comment]
@alpinegizmo @vidma is right, however a dry run wouldn't hurt. specially the fact that the way services are built and stayed might impact the creation of classes, types, or jars etc.
