### ISSUE TITLE
Terms defined should be reset after restarting kernel

### ISSUE THREAD

**Issue by jarutis** [andypetrella/spark-notebook#514]
- [ ] Terms defined should be reset after restarting kernel
  * Currently all defined [terms](https://www.dropbox.com/s/i9065g7rb65txvl/Screenshot%202016-01-07%2013.59.24.png?dl=0) remain the same after restarting kernel.
- [ ] Terms defined should stay present on page refresh (if kernel stays alive or was already running)

cc @vidma

**Comment by vidma** [comment]
nice catch!
