### ISSUE TITLE
improve error message for Request Entity too large

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#527]
- [ ] change error message to something like: `unable to save notebook results, please try selecting less columns`

https://github.com/andypetrella/spark-notebook/commit/3ae23bd7db76aaaae0f1756400d7d3cfa08084c5#diff-2bc81ddbaac9248c65583b4697ee54faR252

**Comment by vidma** [comment]
@andypetrella

**Comment by andypetrella** [comment]
Sure you can increase the limit per instance actually:
https://github.com/andypetrella/spark-notebook/blob/master/conf/application.conf#L94

Changing the message :+1: 

Saving the code only sounds legit :+1:

**Comment by vidma** [comment]
> Saving the code only sounds legit :+1:

hmm but if everything comes as a single request this might be not easy... i.e. the request can be huge...

**Comment by vidma** [comment]
too complex to change error message. let is stay as is.
