### ISSUE TITLE
Observables are lost/broken on page refresh

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#531]
- if original page of notebook is left open with some running cells, and I open another browser tab with same notebook, all works fine - I see updates on both tabs
- BUT if original page is refreshed, the observables get messed up!
  * no link to spark UI
  * no cell /  job progress at all

maybe related to #523 

@andypetrella @meh-ninja

**Comment by andypetrella** [comment]
Ouch nice catch! Need to work on that (I'll try this week though)

**Comment by vidma** [comment]
> Ouch nice catch! Need to work on that (I'll try this week though)

already fixed :tada:
