### ISSUE TITLE
ability to hide/unhide sidebar

### ISSUE THREAD

**Issue by vidma** [andypetrella/spark-notebook#561]
- [x] **do hide/unhide** (switch classes col-9 to col-12 for container)
- [ ] **`hide` link/button**, could be certainly inside (top) of sidebar
- [x] **hide/unhide button**  could be a small little unhide button on top of notebook (right-side), or could also live in somewhere in the menu (but don't fit well)
- [ ] less important: also don't like the sidebar to use js/onscroll magic. it should be a `position: fixed`, but then we need to attach it somewhere elsewhere in the DOM...

cc @andypetrella

**Comment by andypetrella** [comment]
yeah, agreed the position thingie would be better but then I guess we won't be able to use the grid system (that's probably your comment about its position in the DOM right?)

:+1:

**Comment by vidma** [comment]
huh, not sure we need the grid at all.
maybe tabs would be better? (doesn't matter now, this will evolve naturally with new functionality...)

**Comment by andypetrella** [comment]
sure, the grid isn't necessary, I was more thinking about the refactoring.

Also, I'm wondering if have a real grid system like gridster that would also manage the main notebook would be interesting (then we can arrange at our will).

Anyway, show/hide is :+1: 

Also, we'd probably need a menu for tuning the panels we'd like to show out-there (and an api to add/register new ones)

**Comment by vidma** [comment]
> like gridster that would also manage the main notebook would be interesting (then we can arrange at our will).

- maybe better think about contextual menus around each cell for "up" & `down` buttons.
- also multi-column arrangement makes no sense until we have no doc/title per graph/per cell. not yet sure, but maybe it would make sense to allow to attach `markdown` directly to a cell?
