### ISSUE TITLE
Windows, metadata: if "customDeps" contains a local jar, then the sparkContext is undefined

### ISSUE THREAD

**Issue by deanwampler** [andypetrella/spark-notebook#563]
While running with notebooks in Windows, I found that unless the metadata's `customDeps` omits my application code jar file, or the whole `customDeps` is defined to be `null`, then the `sparkContext` (alias `sc`) is undefined. That is, if the metadata has this:

```
customDeps: null,
```

or perhaps this, 

```
customDeps: [ 
  "- org.apache.spark % _ % _", 
  "- org.apache.hadoop % _ % _" ],
```

then it works fine, but if `customDeps` includes this:

```
customDeps: [
    "com.myco %% myapp % 1.0"
],
```

then the `sparkContext` is undefined.

The `customLocalRepo` is defined correctly, as an important statement from my jar file works correctly. Also, if I remove the "myapp" dependency from `customDeps` and use the `:dp` directive instead, that works fine.

**Comment by andypetrella** [comment]
damn it, since I do not have a windows box, to gain some time (meanwhile, I'll try to find one...), could paste here or in a private chat room on gitter (if there is something sensible) the full browser logs you have for this one.

The easiest is probably to open the developer console and select everything (I think ctrl+a works).

Thanks

ps: there might be some info about jar resolution and re/tries in there.

**Comment by deanwampler** [comment]
I found the bug by first noticing the following in the notebooks "sn-session" logs:

```
<console>:2: error: invalid escape character
val CustomJars = Array("C:\Users\deanwampler\ex-windows\spark-notebook-0.6.2-scala-2.11.7-spark-1.5.2-hadoop-2.2.0-with-hive-with-parquet\Usersdeanwampler\.ivy2\com\typesafe\play\play-json_2.11\2.3.0\play-json_2.11-2.3.0.jar", "C:\Users\deanwampler\ex-windows\spark-notebook-0.6.2-scala-2.11.7-spark-1.5.2-hadoop-2.2.0-with-hive-with-parquet\Usersdeanwampler\.ivy2\com\typesafe\play\play-functional_2.11\2.3.0\play-functional_2.11-2.3.0.jar",
...
```

This comes from line 125 in `modules/kernel/src/main/scala-2.11/notebook/ReplCalculator.scala` 

```
    |val CustomJars = ${ deps.mkString("Array(\"", "\",\"", "\")") }
```

This ONLY occurs for the Scala 2.11 version where it appears to calculate the `deps` dependencies _twice_, a possible copy-paste error? The first time, which is the only code in the 2.10 version, correctly escapes nested \ in the strings by adding the following: `replaceAll("\\", "\\\\")`. The second version (shown) in 2.11 does not do this, so when the strings are compiled later by the server, they have invalid escapes (\\) in them, triggering a compilation error.

When I run notebooks with a Scala 2.10 build of the notebook, they work correctly.

I would provide a pull request for this, but I can't get Spark Notebook to build at all. I get compile errors on master for both Scala 2.10 and 2.11. Deleting the duplicate code in the 2.11 version of `ReplCalculator` should do it.

**Comment by andypetrella** [comment]
"bloody hell". That's an odd one!!!
Good catch however.

I'm working currently on a branch to allow the server to run without kernel, and I was in the same time trying to remove some duplication. `ReplCalculator` will require quite some work to extract the greater template but it's worth doing it.

I'll create an issue for it. If you can submit a PR that'd be great, thanks a lot!

**Comment by andypetrella** [comment]
@deanwampler ho, forgot the compilation thingies. Could you tell me more about these because right now travis is stable on master, so it might miss some corner cases that you'd have...

**Comment by deanwampler** [comment]
I pulled your latest changes, started `sbt` with no arguments (in the master branch), and got compilation errors in `modules/common/src/main/scala/notebook/front/widgets/package.scala` when I ran the `dist` task. See the attached log.

[spark-notebook-dist-log.txt](https://github.com/andypetrella/spark-notebook/files/102637/spark-notebook-dist-log.txt)

**Comment by andypetrella** [comment]
man... that's weirdo.

Could you run `sbt clean` first?

Also something strange also, it is picking 2.10.4 instead of 2.10.4 :-S

**Comment by deanwampler** [comment]
Okay, it worked to clean first. Not sure what "junk" I had.

Okay, I'll build and test a PR for the fix.

**Comment by deanwampler** [comment]
Submitted https://github.com/andypetrella/spark-notebook/pull/570.

**Comment by andypetrella** [comment]
Hey, this should be fixed now right?

I think there are other issues on windows, we fix those once for all, would be then nice to have them listed over here.

LMK
