### ISSUE TITLE
Release 0.7.0?

### ISSUE THREAD

**Issue by dragos** [andypetrella/spark-notebook#599]
Hey Andy,

It'd be very handy to have a new release (due to Windows issues). Do you think we could have something this week?

**Comment by andypetrella** [comment]
hello @dragos we can work on a 0.6.3 maybe?

I should have some time this week. Poke me on Fri if no news though :-S

**Comment by andypetrella** [comment]
Hey @dragos I've release a 0.6.3 :-)

0.7.0 needs some more massage first IMHO

**Comment by dragos** [comment]
Is 0.6.3 off the master branch?

**Comment by andypetrella** [comment]
yup, I merge master on branch-0.6 first, so it's the latest greatest :-)

**Comment by dragos** [comment]
cool, thanks!
