### ISSUE TITLE
tachyon and port 4040

### ISSUE THREAD

**Issue by smartinsightsfromdata** [andypetrella/spark-notebook#601]
I downloaded andypetrella/spark-notebook:0.6.2-scala-2.11.7-spark-1.6.0-hadoop-2.7.2-with-hive-with-parquet and tried the tachyon notebook demo (one of the few demo I could find of tachyon!).

The demo refers to checking tachyon memory on `localhost:4040`, but this port is not mapped: I even tried to re-launch the docker with -p 4040:4040 with no effect.

Suggestions please?

**Comment by vidma** [comment]
well very likely `localhost:4040`  was supposed to be a link to `Spark UI` (local spark has ports 4040, 4041, ...).
so wait while notebook fully loads, and click `open Spark UI` link in toolbar on the right hand side.
I also advice to use newest (master) notebook version.

if this is the case, demo might need to be updated.

**Comment by smartinsightsfromdata** [comment]
tk!
