### ISSUE TITLE
a.a.OneForOneStrategy - null

### ISSUE THREAD

**Issue by youngjt** [andypetrella/spark-notebook#603]
[error] a.a.OneForOneStrategy - null
java.lang.NullPointerException: null
       at notebook.server.CalcWebSocketService$CalcActor$$anonfun$receive$1.applyOrElse(CalcWebSocketService.scala:143) ~[nooostab.spark-notebook
-0.6.2-scala-2.10.4-spark-1.5.0-hadoop-2.2.0-with-hive-with-parquet.jar:0.6.2-scala-2.10.4-spark-1.5.0-hadoop-2.2.0-with-hive-with-parquet]
       at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[com.typesafe.akka.akka-actor_2.10-2.3.11.jar:na]
       at notebook.server.CalcWebSocketService$CalcActor.aroundReceive(CalcWebSocketService.scala:38) ~[nooostab.spark-notebook-0.6.2-scala-2.10.
4-spark-1.5.0-hadoop-2.2.0-with-hive-with-parquet.jar:0.6.2-scala-2.10.4-spark-1.5.0-hadoop-2.2.0-with-hive-with-parquet]
       at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.10-2.3.11.jar:na]
       at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.10-2.3.11.jar:na]
[info] application - SAVE → Untitled4.snb

**Comment by andypetrella** [comment]
mmmmh, can you elaborate quickly what is the use case?

**Comment by youngjt** [comment]
the detail of my environment configure is :
"yjtYarn" : {                                                                                                                                    
    "profile" : "yarn-client",                                                                                                                   
    "name" : "yjtYarn",                                                                                                                          
    "status" : "stopped",                                                                                                                        
    "template" : {                                                                                                                               
        "customLocalRepo" : "/home/xxxx/.m2/repository",                                                                                    
        "customDeps" : ["med-at-scale % ga4gh-model-java % 0.1.0-SNAPSHOT","org.apache.avro % avro-ipc % 1.7.6","- org.mortbay.jetty %  org.eclip
se.jetty % _"],                                                                                                                                  
        "customImports" : "import scala.util.Random",                                                                                            
        "customArgs" : ["-Dtest=ok","-Dyarn.resourcemanager.am.max-attempts=1"],                                                                 
        "customSparkConf" : {                                                                                                                    
            "spark.app.name" : "yjtYarnSC",                                                                                                      
            "spark.master" : "yarn-client",                                                                                                      
            "spark.executor.memory" : "4G",                                                                                                      
            "spark.yarn.jar" : "hdfs://xxxxx/spark-assembly-1.5.1-SNAPSHOT-hadoop2.2.0.jar"                                             
        }                                                                                                                                        
    }                                                                                                                                            
  }

when i create a yarn-client notebook,i find that it can not link to my spark cluster?
And now the showing info is :
Spawning [/software/servers/jdk1.7.0_67/jre/bin/java, -Xmx7478968320, -XX:MaxPermSize=1073741824, -server, -Dtest=ok, -Dyarn
.resourcemanager.am.max-attempts=1, notebook.kernel.pfork.ChildProcessMain, notebook.kernel.remote.RemoteActorProcess, 16803, info, 7f1e3da2-e39a
-4051-a773-fcc7d5056450, Untitled6.snb, kernel, ]
[info] application - In working directory .
[info] application - Registering first web-socket (notebook.server.WebSockWrapperImpl@5e398c3f) in service notebook.server.CalcWebSocketService$C
alcActor@1426ac6d

where is the error? and the last error does not appear.

thanks.
