### ISSUE TITLE
Problem with Dependencies

### ISSUE THREAD

**Issue by lenguyenhaohiep** [andypetrella/spark-notebook#617]
I'm using spark-notebook with scala 2.10.4, hadoop 2.7.1 and spark 1.4.1 run on yarn-client
When I use spark-csv dependency, I add

"customDeps": [
    "com.databricks:spark-csv_2.10:**1.0.3**"
],

However, I have an error

java.io.InvalidClassException: com.databricks.spark.csv.CsvRelation; local class incompatible: stream classdesc serialVersionUID = -8000178435135078983, local class serialVersionUID = 4060835725101693206

I found that spark-notebook uses libraries stored in the SPARK_NOTEBOOK_HOME/lib to compile the code, it means that it uses **com.databricks.spark-csv_2.10-1.3.0.ja**r (serialVersionUID = -8000178435135078983) but in every node, spark will use version 1.0.3 (serialVersionUID = 4060835725101693206)

So I tried to fix this problem, there are two ways
#1: Go to this lib folder and remove the .jar file with different version
#2: Use the same version with the one in the lib folder, it means I changed 
"customDeps": [
    "com.databricks:spark-csv_2.10:**1.3.0**"
]

Any idea?
Cheers,

**Comment by vidma** [comment]
for now, try to use the same version as in `spark-notebook`. 

we'll check if that could be compiled as a `provided` dependency (but means `customDeps` would need to have this set explicitly, or we'd need to append defaults).

**Comment by vidma** [comment]
btw, @lenguyenhaohiep spark 1.4.1 is damp old! go ahead and use `spark 1.6.0` or `spark 1.6.0` - it's much faster/have new features. compiling it is easy, and works like charm.

**Comment by sam75** [comment]
Hi,

I am getting the following error:

"
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, hadoop-slave1): java.io.InvalidClassException: com.databricks.spark.csv.CsvRelation; local class incompatible: stream classdesc serialVersionUID = 2004612352657595167, local class serialVersionUID = -8000178435135078983"

I am trying to run with spark 1.5.2 and I am having the following dependency:

<dependency>
    <groupId>com.databricks</groupId>
    <artifactId>spark-csv_2.10</artifactId>
    <version>1.4.0</version>
</dependency>

**Comment by lenguyenhaohiep** [comment]
@sam75 Can you check the spark-csv version in the folder lib of spark-notebook whether it is the version 1.4.0
If not, can you try one of followings:
1/ Remove the spark-csv file in the lib folder
2/ Use the same version as in the lib folder.

**Comment by andypetrella** [comment]
@lenguyenhaohiep @vidma I'm wondering if we shouldn't remove it, since I've heard many times that it was causing problems...
Also in spark 2.0.0 there will be a native csv support

**Comment by vidma** [comment]
agree, once spark 2.0 becomes stable (it's a mess still), we should remove the dependencies.
