### ISSUE TITLE
log4j:WARN 

### ISSUE THREAD

**Issue by Isaacsh** [andypetrella/spark-notebook#618]
Hello

I am having a problem when try to run (spark-notebook-0.6.3-scala-2.10.4-spark-1.4.1-hadoop-2.7.1). After unzipping, I logged in to my Hadoop cluster, changed to the root directory of the unzipped distribution and run the following command:

`./bin/spark-notebook`

But it produced the following warnings and then stops:

`Play server process ID is 22128`
`SLF4J: Class path contains multiple SLF4J bindings.`
`SLF4J: Found binding in [jar:file:/s/ishams/spark-notebook-0.6.3-scala-2.10.4-spark-1.4.1-hadoop-2.7.1/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]`
`SLF4J: Found binding in [jar:file:/s/ishams/spark-notebook-0.6.3-scala-2.10.4-spark-1.4.1-hadoop-2.7.1/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]`
`SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.`
`SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]`
`log4j:WARN No appenders could be found for logger (net.sf.ehcache.config.ConfigurationFactory).`
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

Appreciate any helpful comments!

**Comment by dengelha** [comment]
Hey guys,

I am facing exactly the same issue trying to get it runnin for Spark 1.6.1 on Ubuntu 16.04 LTS server.

`bin/spark-notebook`
 
`Play server process ID is 14937
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark-notebook/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark-notebook/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (net.sf.ehcache.config.ConfigurationFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
`

Two days of googling and experimenting didn't help. So, I am beggin the awesome @andypetrella for a lil support. Thank you in advance !!!

**Comment by dengelha** [comment]
Hey @Isaacsh ,

I had a nice chat with @andypetrella and Adam about the issue. It turns out, we have to blame our proxy-server or the firewall. So, it is no Spark-Notebook issue. When I "tear down the wall", I can catch the Spark-Notebook on port 9000 (default).
I am currently working on the proxy the have a password protection enabled.

Thanks again to Andy and Adam, awesome support and really, really friendly !

**Comment by Isaacsh** [comment]
@dengelha 

Thanks for your helpful comment. Never have thought about firewall being the issue. Please post in case you nail it.

**Comment by dengelha** [comment]
Hey @Isaacsh ,

I desperately worked on that and tested all the NGINX configurations. No solution on the SSL + password protection yet, as neither the awesome Spark-Notebook nor NGINX can find their way to the assets. Therefore, I get lots of 404 on css, png ... analyzing the browser behavior when accessing the https://...:9000.

But are you dependent on the password protection? You can also build an open tunnel for 9000 to localhost:9000 via putty. Then, you can access SNB on your server via the browser of your client PC.

What do you thing?
Enjoy coding :-)

David

**Comment by Isaacsh** [comment]
Thanks @dengelha It works on localhost:9000 via putty
