### ISSUE TITLE
Native aggregation function cant be found when using agg on a DataFrame

### ISSUE THREAD

**Issue by ndjido** [andypetrella/spark-notebook#623]
Hi,

I'm using Spark-notebook 0.6.3 on Spark 1.5.2 and native aggregation functions like **min, max, avg ** cant be found by the interpreter .

code example:
**val df_result = df.select("A", "B", "C").groupBy("A", "B")
                                                          .agg(min(df("B").as("minB"))**

**Comment by vidma** [comment]
isn't that you have to import these functions? 
like ```scala
import org.apache.spark.sql.functions._
``` 

which scala version?

**Comment by andypetrella** [comment]
yes it has to be imported, it can be done in the next version indeed. 

Also, right now,  you could consider putting this import into the configuration file, in the override section. so that all started notebooks will have it!

**Comment by ndjido** [comment]
That makes sense! This works with import org.apache.spark.sql.functions._ .

Thx a lot.
