### ISSUE TITLE
$"columnName" not supported 

### ISSUE THREAD

**Issue by ndjido** [andypetrella/spark-notebook#625]
Hi,

When trying to create new features in my DataFrame using $"columnName" pattern, the interpreter runs into an error. Is there any work-arround to make work except the use of the DataFrame name.

code example:
**
val df_v2 = df.withColumn("A_v2", myUDF($"A_v1"))**

**Comment by andypetrella** [comment]
weird I use that all the time what error did you for?

**Comment by ndjido** [comment]
I'm getting the following error:

**error: value $ is not a member of StringContext
**

**Comment by vidma** [comment]
I'm pretty sure this is not at all notebook related. please look at the examples first.

I feel like you again need some import:
```scala
import sqlContext.implicits._
// only now  the $"columnName" is available
```

**Comment by ndjido** [comment]
@vidma you're right, I'm more familiar to Zeppelin where all these things works out of the box. 

Thx!
