### ISSUE TITLE
spark.app.name is overwritten

### ISSUE THREAD

**Issue by eualin** [andypetrella/spark-notebook#630]
I have noticed that spark notebook ignores the `spark.app.name` I have set within the `Notebook Metadata` in favour of the notebook name itself e.g. `spark.app.name=Test.snb`. Is this a bug or a misconfiguration on the notebook metadata?

> {
>       "name": "notebook",
>       "user_save_timestamp": "1970-01-01T00:00:00.000Z",
>       "auto_save_timestamp": "1970-01-01T00:00:00.000Z",
>       "language_info": {
>         "name": "scala",
>         "file_extension": "scala",
>         "codemirror_mode": "text/x-scala"
>       },
>       "trusted": true,
>       "customLocalRepo": "notebook",
>       "customRepos": null,
>       "customDeps": null,
>       "customImports": null,
>       "customArgs": null,
>       "customSparkConf": {
>         "spark.cores.max": "4",
>         "spark.master": "spark://172.17.0.2:7077",
>         "spark.app.name": "notebook",
>         "spark.executor.memory": "4G"
>       },
>       "kernelspec": {
>         "name": "notebook",
>         "display_name": "notebook"
>       }
> }

**Comment by vidma** [comment]
if I remember well, it's being overridden by `notebook file name` (which is default if you don't set it), which allows to consistently identify which notebook is running.

why do you need `spark.app.name` at all?
