### ISSUE TITLE
Error loading (valid ?) notebook

### ISSUE THREAD

**Issue by pmid** [andypetrella/spark-notebook#631]
I'm trying to load a notebook taken from Big Data University "Spark Fundamentals"
course, and I get the error 

`"Error loading notebook
An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details."`

The notebook is a valid json file; it seems that the issue arises because source are defined as arrays (e.g.    
`"source": [
    "The bigger the dataset, the more noticeable the difference will be. In a sample file such as ours, the difference may be negligible."
   ]`

I attach both the notebook and the error log file.

I tried with the nightly build (spark-notebook-0.6.3-scala-2.11.7-spark-1.6.1-hadoop-2.2.0), with (spark-notebook-0.6.3-scala-2.10.4-spark-1.5.2-hadoop-2.6.0) and (spark-notebook-0.6.3-scala-2.11.7-spark-1.6.1-hadoop-2.7.1), the problem is the same.

Thanks,

Paolo

[bdu.zip](https://github.com/andypetrella/spark-notebook/files/201066/bdu.zip)

**Comment by andypetrella** [comment]
Hello Paolo,

I've made some checks, it may be valid, but it didn't pass the spark notebook validator, so I had to make some changes:
* "source" were arrays → I joined the value into a string which is the expected type for the spark notebook (so far at least)
* missed a "name", "user_save_timestamp" and "auto_save_timestamp" metadata that I added
* I removed the execution_count (it might not be necessary).

I attached the result (as txt...)
[bdd1.snb.txt](https://github.com/andypetrella/spark-notebook/files/201121/bdd1.snb.txt)

I wondering one thing: which tool did generated this file?

Second question, if this kind of file with this structure are worth to be considered valid, so it'd be interesting to create a dedicate enhancement issue with the example :-).

thanks
andy

**Comment by pmid** [comment]
Hi Andy,

thanks a lot for yout prompt reply, and for the working notebook too.

I don't know which tool generated the file I attached: I registered to the "Spark Fundamentals I" course on BgDataUniversity (http://bigdatauniversity.com/courses/spark-fundamentals/).
Upon registration we should be provided with a demo access to the IBM Analytcs / Data Scientist Workbench : "Data Scientist Workbench is a collection of tools making open source data science easy. You can connect from many of the tools in Data Scientist Workbench to the Big SQL Technology Sandbox environment in order to access powerful, parallelized computing capacity.

This set of labs uses Data Scientist Workbench to provide an interactive environment to develop applications and analyze data. It is available in either Scala or Python shells."

I requested the access five days ago, but I haven't yet received the mail which notifies the activation, so I decided to install the notebooks for python and Scala, and try locally the notebooks they provide.

Coming to your second question, I must admint that my experience with Spark amount to... one week, so I'm afraid I'm not the right person to state if "if this kind of file with this structure are worth to be considered valid" : I have no clue at all! :-)
If you wish, I'll create the enhancement issue, but I'll let the choice to you.

Thanks again,

Paolo

**Comment by pmid** [comment]
Hi Andy, just a quick update...
I was finally granted access to the IBM cloud environment. The notebook should be executed with the Jupyter Notebook, so I deduce it's been generated with it, too.

**Comment by andypetrella** [comment]
Oh okay, actually the changes are that big, and worth considering (at least the array for the source). So we can work on that support!
