### ISSUE TITLE
Hortonworks Distro doesn't comple

### ISSUE THREAD

**Issue by agibsonccc** [andypetrella/spark-notebook#656]
https://gist.github.com/agibsonccc/5c15d6b8637619a2c8f8ce99039c5900

This is likely solved by adding the horton works repo:
http://repo.hortonworks.com/content/repositories/releases/

**Comment by huitseeker** [comment]
What's your full compilation sbt invocation ?

**Comment by andypetrella** [comment]
@agibsonccc mmmmh, the  @huitseeker request would help us, this is a parsing problem

after that I'm expecting a repos to be missed to fetch the deps, but before that, we need to check what is the spark version

tx :-)
