### ISSUE TITLE
Metadata window needs a scrollbar if the json is too wide to be displayed/edited

### ISSUE THREAD

**Issue by NicolasRouquette** [andypetrella/spark-notebook#660]
With Edit > Edit Notebook Metadata, a new modal window is displayed inside the browser window. It is possible for the json metadata to be to wide to fit inside the  modal window in which case the overflow is shown and is editable as long as it is within the browser window. Beyond that, the overflow is not visible. 

Suggest adding horizontal & vertical scrollbars.

**Comment by vidma** [comment]
only vertical scrollbar missing. shall be easy.

**Comment by vidma** [comment]
fixed in #813
