### ISSUE TITLE
Auto shut-down of idle notebooks

### ISSUE THREAD

**Issue by raproth** [andypetrella/spark-notebook#676]
Is there a way to shut down running notebooks after a certain time? In our team, people often forget to shut down their notebooks and thus unnecessarily consuming resources...

**Comment by vidma** [comment]
yes, just use this: `./bin/spark-notebook "-Dmanager.kernel.killTimeout=180 minutes"`
see #526

we also use dynamic allocation:
```
-Dmanager.notebooks.override.sparkConf.spark.dynamicAllocation.initialExecutors=1 \
 -Dmanager.notebooks.override.sparkConf.spark.dynamicAllocation.minExecutors=0  \
 -Dmanager.notebooks.override.sparkConf.spark.dynamicAllocation.cachedExecutorIdleTimeout=10min \
```
