### ISSUE TITLE
Optimizing resource needed by a notebook

### ISSUE THREAD

**Issue by raproth** [andypetrella/spark-notebook#677]
As we are working as a team on a spark notebook server, we have easily 10 notebooks running simultaneously. Strangely, we cannot run more than 12 notebooks in parallel, the new ones will just not start up. Although I'm not sure if this is an memory issue, I wonder how one can tune the resources (especially memory) taken by the notebooks and/or increase the maximum number of running notebooks?

**Comment by vidma** [comment]
In most case spark `driver` starts on the machine as `notebook web server`, so you have these options:
- reduce memory allocated to the spark driver
- just use a normal server with more ram for the notebook.

we use a relatively poor machine 128GB ram. no problem for like 30 notebooks.
