### ISSUE TITLE
The pull command given in build success email is incorrect

### ISSUE THREAD

**Issue by davidshen84** [andypetrella/spark-notebook#684]
I requested a new build on the web, and got a success email with pull instruction:

> docker pull andypetrella/spark-notebook:master-scala-2.11.8-spark-2.0.0-hadoop-2.7.2
> docker run -p 9000:9000 andypetrella/spark-notebook:master-scala-2.11.8-spark-2.0.0-hadoop-2.7.2

However, it does not work. If I go to https://hub.docker.com/r/andypetrella/spark-notebook/tags/, I found my build is tagged with *0.7.0-SNAPSHOT-scala-2.11.8-spark-2.0.0-hadoop-2.7.2*.

I guess you forgot to update the notification email template :)

Not a big issue. Just to let you know, if you want to update the template.

**Comment by andypetrella** [comment]
Thanks! I changed that :-)
