### ISSUE TITLE
Too many validation buttons

### ISSUE THREAD

**Issue by jarutis** [andypetrella/spark-notebook#688]
Hi,

That validate output button is replicating :)

<img width="1190" alt="screenshot 2016-08-17 22 00 15" src="https://cloud.githubusercontent.com/assets/3201415/17749450/5b18304e-64c6-11e6-967e-385f31a183f5.png">

cc @andypetrella

**Comment by andypetrella** [comment]
aahahahahaha .... ok, need to fix that shit ^^
