### ISSUE TITLE
Not able to connect to Hive metastore with Spark-2.0.0 on current master

### ISSUE THREAD

**Issue by james64** [andypetrella/spark-notebook#705]
Hey,
I mentioned this few times in gitter but let's move the discussion here. The issue is that I can connect to our company's hive metastore using this version:
*spark-notebook-0.6.3-scala-2.10.5-spark-1.6.2-hadoop-2.6.0-cdh5.7.1-with-hive-with-parquet*

But I am not able to do that with this version
*spark-notebook-master-scala-2.11.8-spark-2.0.0-hadoop-2.6.0-cdh5.7.1-with-hive*

This is what I do to try if I can connect to metastore:
```scala
val spark = SparkSession.builder.enableHiveSupport.getOrCreate
spark.catalog.listTables("<db_name>")
```

Result is an exception that the database does not exist. The same happens when i try to use HiveContext which makes sense because HiveContext in spark2.0.0 is forwarding all calls to sparkSession.

What I already know:
1. this works in spark-2.0.0 spark-shell
2. Exeption about non existing database is raised from `org.apache.spark.sql.internal.CatalogImpl` class
3. `spark.conf.getAll` contains "spark.sql.catalogImplementation" = "hive"
4. During call to `getOrCreate` (see above) I see these messages in logs:
2016-09-28 16:14:53,916  WARN [Remote-akka.actor.default-dispatcher-4] (org.apache.spark.SparkContext) - Use an existing SparkContext, some configuration may not take effect.
2016-09-28 16:15:54,174  WARN [Remote-akka.actor.default-dispatcher-3] (org.apache.spark.sql.SparkSession$Builder) - Use an existing SparkSession, some configuration may not take effect.
5. `spark.sparkContext.hadoopConfiguration` contains all entries from hive-site.xml on classpath

Looking into the source one can see that [2] is an default implementation of `SparkSession.catalog` which is overwritten in case some external system like hive is to be used. The fact that an exception came from [2] means that it was not overwritten by `org.apache.spark.sql.hive.HiveExternalCatalog` which is to be used for interaction with hive. The fact that this catalog implementation is to be used is documented by [3]. Option [3] is set as result of call to `.enableHiveSupport` on session builder. But since it is not set and also log messages [4] I assume there is something wrong with the way how sparkContext/Session are initialized...

**Comment by james64** [comment]
Initialization code was too complicated for me to investigate further.
@andypetrella I see that you would need to investigate this before we can solve it so I do not expect some quick solution to this. But I would appreciate if this will not die away without any eventual resolution.

Please do let me know if I can add some more relevant info.

**Comment by vidma** [comment]
notice that `spark 2.0` support lives in [`future-master` branch](https://github.com/andypetrella/spark-notebook/tree/future-master) and not in `master` (I don't know how you downloaded it...). myself, I still need to take a careful look at what lives there...

please update on how it goes.
looks like `spark 2.0.1` is close to being released!  🎉

**Comment by james64** [comment]
@vidma I download the jar from spark-notebook.io site. I chose notebook version master as advised there for spark 2.0.x. I have no idea which branch is used there to compile. I can try to compile the notebook myself. If the helps then spark-notebook.io has an issue to fix...

**Comment by andypetrella** [comment]
yeah 2.0.1... finally something a bit more stable I hope

The generator takes care of this branches schizophrenia  :-)

**Comment by andypetrella** [comment]
could you maybe try to not create the session yourself and only using the metadata (customSparkConf) ?

That might be a problem since some stuff are being injected in the configuration from the classpath and other things to make sure it'll work.

Here you create a bare SparkSession that might not even use the hive information (thinking live, to take with a pinch of salt)

**Comment by james64** [comment]
@andypetrella I will try this once I find a bit of time for that. Can you please in meantime elaborate a bit on what you mean by using the metadata? It is that I should by pass all configuration of notebook and create completely new and independent sparkContext like this?

```val conf = new SparkConf().set(...).set(...) ...
val sc = new SparkContext(conf)```

or something else?

Thanks

**Comment by james64** [comment]
I tried to add `spark.sql.catalogImplementation=hive` into custom sparkConf of my job. It did solve the problem. I understand that solving this so I do not need this workaround is kinda in progress now as part of move-to-spark2.* initiative. Is this right?

Thanks

**Comment by vidma** [comment]
I guess this could be enabled automatically if notebook is built with Hive support.

in the meantime to can enforce this setting for all notebooks when starting the service:
something like:

```bash
./bin/spark-notebook \
  -Dmanager.notebooks.override.sparkConf.spark.sql.catalogImplementation=hive
```

**Comment by james64** [comment]
[FYI] I use notebook built with hive support from the very beginning:
`spark-notebook-master-scala-2.11.8-spark-2.0.0-hadoop-2.6.0-cdh5.7.1-with-hive`

**Comment by iching-long** [comment]
It works on spark-2.1.0 too！Thanks!
@vidma @james64
