### ISSUE TITLE
S3 link format

### ISSUE THREAD

**Issue by AustinBGibbons** [andypetrella/spark-notebook#71]
Clicking the S3 link from: https://github.com/andypetrella/spark-notebook/releases

Gives me:
![screenshot 2015-01-22 10 33 41](https://cloud.githubusercontent.com/assets/1144402/5861890/467b0dae-a222-11e4-8af1-c4fab5b0e781.png)

Is that expected, instead of a directory hierarchy?

**Comment by andypetrella** [comment]
agreed it's not *that* user friendly!
I'll try to add some html file to, at least, list 'em.

**Comment by andypetrella** [comment]
Quick and dirty but does the work ;-)
[http://s3.eu-central-1.amazonaws.com/spark-notebook/index.html](http://s3.eu-central-1.amazonaws.com/spark-notebook/index.html)
