### ISSUE TITLE
Fix Autocompletion for 2.11 :-(

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [andypetrella/spark-notebook#726]

**Comment by andypetrella** [comment]
I think you're on scala 2.11 which needs a refactoring of the completion. Am I right ?

**Comment by alexDeCastroAtGit** [comment]
Yes, I'm on scala 2.11:-)
Refactoring on their side on our side here? 
Yes, I get no autocompletion at all so I've been navigating classes with 
<Class>.getClass.getMethods.map(_.getName) and some regex

**Comment by andypetrella** [comment]
warf sorry man

this is some refactoring on our side :-(

**Comment by antonkulaga** [comment]
Absence of autocompletion makes spark-notebook useless for me as :_(
Please, fix!

**Comment by vidma** [comment]
👍 , we'll make sure that there's a least some temporal solution for this soon!
