### ISSUE TITLE
How to load mysql driver using spark-notebook?

### ISSUE THREAD

**Issue by hujianxin** [andypetrella/spark-notebook#732]
Hi, I have downloaded mysql's diver into lib, but spark-notebook can not find it. How to solve this problem? Thanks

**Comment by andypetrella** [comment]
Mmmmh I think the driver is quite touchy with Spark and REPL, I think (again) that it's better to have it loaded quite early.

First question: you put it into the lib folder of the installation?

**Comment by hujianxin** [comment]
@andypetrella Yes, I have already put it in lib folder.

**Comment by andypetrella** [comment]
Could you use the `customDeps` instead? 

Putting it in the `lib` won't put it in the spark jars :-S

**Comment by hujianxin** [comment]
@andypetrella Thanks a lot!
