### ISSUE TITLE
Adding horizontal scroll bar to cell when needed

### ISSUE THREAD

**Issue by quertenmont** [andypetrella/spark-notebook#768]
@vidma 
Can we add an horizontal scroll bar to the cells (or alternatively to the web page) when needed ?

Everytime I print the content of dataframes with many column it's a pain to see the last ones
![image](https://cloud.githubusercontent.com/assets/4639944/21590914/eb4e2394-d0ff-11e6-8fd4-24988d1cc528.png)

**Comment by vidma** [comment]
👍 will check this. should be easy.
