### ISSUE TITLE
Run notebook on mesos

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#77]
"Executor Spark home `spark.mesos.executor.home` is not set!" even if `spark.executor.uri` is correctly set

**Comment by djamelz** [comment]
Yep,
After set the SPARK_HOME, the error is not throw but the task never answers however the Mesos console indicates that the framework is still there...

Below the log :

I0125 23:06:16.778283 11383 sched.cpp:391] Framework registered with 20141204-192239-117451018-5050-8266-0083
[INFO] Load notebook: Untitled15
[INFO] Load notebook. basePath: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook. file name: Untitled15.snb
[INFO] Load notebook. canonical file path: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook: Untitled15
[INFO] Load notebook. basePath: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook. file name: Untitled15.snb
[INFO] Load notebook. canonical file path: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook: Untitled15
[INFO] Load notebook. basePath: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook. file name: Untitled15.snb
[INFO] Load notebook. canonical file path: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook: Untitled15
[INFO] Load notebook. basePath: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[INFO] Load notebook. file name: Untitled15.snb
[INFO] Load notebook. canonical file path: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks
[WARN] Termination
[WARN] Termination
W0125 23:06:48.534540 11388 sched.cpp:901] Attempting to launch task 1 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534700 11388 sched.cpp:901] Attempting to launch task 2 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534751 11388 sched.cpp:901] Attempting to launch task 3 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534797 11388 sched.cpp:901] Attempting to launch task 4 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534844 11388 sched.cpp:901] Attempting to launch task 5 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534889 11388 sched.cpp:901] Attempting to launch task 6 with an unknown offer 20141204-192239-117451018-5050-8266-34077
W0125 23:06:48.534935 11388 sched.cpp:901] Attempting to launch task 7 with an unknown offer 20141204-192239-117451018-5050-8266-34077
[INFO] Load notebook: Untitled15
[INFO] Load notebook. basePath: /home/djamelz/spark-notebook-0.1.4-spark-1.2.0-hadoop-2.0.0-cdh4.2.0/conf/notebooks

**Comment by andypetrella** [comment]
okay, the applications has some tasks assigned and running in the mesos UI?
I used to use mesos several times, and it's never easy to debug in this env ;-).

Could you also check the spark UI? See if it has some tasks as well.

Last but not least, the mesos logs are reporting something about this job?

**Comment by djamelz** [comment]
It seems that the kernel didn't keep the connection alive (I change the name of node by MesosNode & SparkNotebookNode) :

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 28, MesosNode): java.io.IOException: Connection from SparkNotebookNode/10.41.0.40:38482 closed

**Comment by andypetrella** [comment]
really? weirdo!

I never encounter this problem yet. Do you experience the connection to be closed by the driver?

Oh, perhaps: Is SparkNotebookNode accessible by the MesosNode? No firewall or nat specificities there?

**Comment by djamelz** [comment]
I can launch and use a spark-shell with the same configuration. 
I will try to find & thx for the help.

**Comment by andypetrella** [comment]
okay, that's a good point. I'll see on my mesos cluster this week what's going on as well. Don't hesitate to poke me by mail or chat if you like!

**Comment by andypetrella** [comment]
I created a gitter room for live discussions. It'll be easier that via comments.
https://gitter.im/andypetrella/spark-notebook

**Comment by andypetrella** [comment]
heya @djamelz , did you find some time to try again :-P ?

**Comment by djamelz** [comment]
Yep, yesterday.
And I think it's an issue with the driver name send to mesos. It seems the worker node want to connect to the driver with the url dnsname/ipaddress:54104 instead of dnsname:54104 or ipaddress:54104 as you can see on this log:

15/01/26 10:42:32 ERROR client.TransportResponseHandler: Still have 1 requests outstanding when connection from DriverNode/10.41.0.40:54104 is closed
15/01/26 10:42:32 ERROR shuffle.OneForOneBlockFetcher: Failed while starting block fetches
java.io.IOException: Connection from DriverNode/10.41.0.40:54104 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelUnregistered(TransportResponseHandler.java:98)
	at org.apache.spark.network.server.TransportChannelHandler.channelUnregistered(TransportChannelHandler.java:81)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:183)

WDYT ?

**Comment by andypetrella** [comment]
strange, and even stranger if it's the notebook culprit.
Does that happen even when you set up the driver host in the spark conf?

**Comment by djamelz** [comment]
I tried with an env var like this :
export SPARK_DRIVER_HOST=DriverDnsName

but same issue.

**Comment by andypetrella** [comment]
Would you mind posting your `sparkContext.getConf.toDebugString`?
Of both the notebook and the other application running "natively" in mesos?

That should help debugging, since it's very low level.

Also check the memory allocated to the workers? The trick here is communcation between workers and drivers during a shuffle right?

**Comment by djamelz** [comment]
res1: String = 
spark.app.id=20141204-192239-117451018-5050-8266-0117
spark.app.name=Notebook
spark.driver.host=DriverNode
spark.driver.port=41081
spark.executor.id=driver
spark.executor.uri=hdfs:///user/mesos/executors/spark/spark-1.2.0-bin-cdh4.1.2.tgz
spark.fileserver.uri=http://10.41.0.40:51347
spark.home=/home/djamelz/spark-1.2.0-bin-cdh4.1.2/
spark.jars=
spark.master=mesos://zk://zookeeperNode:2181/mesos
spark.repl.class.uri=http://10.41.0.40:59726
spark.tachyonStore.folderName=spark-35d59c97-d5da-49eb-ab76-e6867e712471

(10.41.0.40 is the DriverNode ip address)

Concerning the job, even a simple job encountered the issue, for instance:
sparkContext.parallelize(1 to 10000).count

**Comment by andypetrella** [comment]
might it be the hadoop version? cdh4.1.2 over cdh4.2.0
Would surprise me, specially if the other jobs are using the same one.

So even a simple parallelize would fail.... argl I've no real other idea atm.

Would be great to discuss that on gitter when you'll have some time...

**Comment by andypetrella** [comment]
If you have any chance to try it out with the current branch it'd be great.
It should have been fixed while removing any other deps to guava.
Actually, I've met this issue myself and figured out that a bad version of guava was messing around in the workre :-S.

**Comment by andypetrella** [comment]
I've just tried using it on my mesos, when all conf are there and right. It works quite well 

I even access a cassandra ring using the notebook deployed on a mesos cluster with spark workers... so complex enough :-D.

I'll close this issue, feel free to reopen it if it still don't work.

**Comment by djamelz** [comment]
Hey Andy, good news: I've just tested and it works !!!

Thx !

**Comment by andypetrella** [comment]
woohooo, you made my day :-D
