### ISSUE TITLE
Can't load notebook.kernel.pfork.ChildProcessMain

### ISSUE THREAD

**Issue by Umit-Mert** [andypetrella/spark-notebook#775]
Hi,

I cloned master branch and run:
sbt compile
sbt run

When I create a new notebook and run println("hey"), getting below error:

Error: Could not find or load main class notebook.kernel.pfork.ChildProcessMain
[error] application - Process exited with an error: 1 (Exit value: 1)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:745)

Right before this error, I have below Warning
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0

I have java version
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Same thing happens when I download latest release from spark-notebook.io

Hope somebody can help. Thank you.
Best,
Umit

**Comment by vidma** [comment]
did: `spark-notebook git:(master) ✗ sbt clean compile run`
I also got the same message, but it works just fine for me (on older `java version "1.8.0_92"`)
 ```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0
```

- If you used `spark-notebook` earlier, maybe you forgot the `clean` ?
- is there anything else in the log?

**Comment by Umit-Mert** [comment]
I run sbt clean compile run, but didn't help. I'm pasting full log after running "sbt clean compile run" and there some warnings about resolvers.

~/Desktop/+Spark_Notebook/spark-notebook$sbt clean compile run
[info] Loading project definition from /Users/umit/Desktop/+Spark_Notebook/spark-notebook/project
[info] Set current project to spark-notebook (in build file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/)
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[success] Total time: 0 s, completed Jan 12, 2017 11:18:58 AM
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}spark-notebook-core...
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}subprocess...
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}sbt-dependency-manager...
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.3.2 ...
[info] Compiling 3 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/core/target/scala-2.10/classes...
[info] Resolving org.easytesting#fest-util;1.1.6 ...
[info] Done updating.
[info] Resolving org.scala-sbt#sbt;0.13.8 ...
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}observable...
[info] Resolving org.scala-sbt#process;0.13.8 ...
[info] Compiling 5 Scala sources and 1 Java source to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/subprocess/target/scala-2.10/classes...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Resolving org.scala-stm#scala-stm_2.10;0.7 ...
[info] Compiling 3 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/sbt-dependency-manager/target/scala-2.10/classes...
[info] Resolving org.apache.hadoop#hadoop-yarn-server;2.2.0 ...
[info] Done updating.
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}common...
[info] Resolving org.apache.avro#avro-toplevel;1.7.7 ...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[warn] there were 2 feature warning(s); re-run with -feature for details
[warn] one warning found
[info] Resolving org.apache#apache;10 ...
[info] Compiling 9 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/observable/target/scala-2.10/classes...
[info] Resolving org.apache.hadoop#hadoop-yarn-server;2.2.0 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}spark...
[info] Resolving org.apache.spark#spark-parent_2.10;2.0.1 ...
[warn] /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/observable/src/main/scala/notebook/ObsWebSocketService.scala:29: non-variable type argument play.api.libs.json.JsValue in type pattern play.api.libs.iteratee.Concurrent.Channel[play.api.libs.json.JsValue] is unchecked since it is eliminated by erasure
[warn]       case m@("add", channel: Concurrent.Channel[JsValue]) =>
[warn]                                          ^
[warn] /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/observable/src/main/scala/notebook/ObsWebSocketService.scala:32: non-variable type argument play.api.libs.json.JsValue in type pattern play.api.libs.iteratee.Concurrent.Channel[play.api.libs.json.JsValue] is unchecked since it is eliminated by erasure
[warn]       case m@("remove", channel: Concurrent.Channel[JsValue]) =>
[warn]                                             ^
[info] Resolving org.apache#apache;14 ...
[warn] there were 2 feature warning(s); re-run with -feature for details
[warn] three warnings found
[info] Compiling 43 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/common/target/scala-2.10/classes...
[info] Resolving org.apache.hadoop#hadoop-yarn-server;2.2.0 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}kernel...
[info] Resolving org.apache#apache;10 ...
[warn] there were 3 deprecation warning(s); re-run with -deprecation for details
[warn] there were 17 feature warning(s); re-run with -feature for details
[warn] two warnings found
[info] Compiling 6 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/spark/target/scala-2.10/classes...
[info] Resolving org.apache.hadoop#hadoop-yarn-server;2.2.0 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating {file:/Users/umit/Desktop/+Spark_Notebook/spark-notebook/}sparkNotebook...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[info] Compiling 6 Scala sources to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/kernel/target/scala-2.10/classes...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:14.0.1 -> 16.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 17 Scala sources and 1 Java source to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/target/scala-2.10/classes...
[warn] /Users/umit/Desktop/+Spark_Notebook/spark-notebook/app/controllers/Application.scala:252: non-variable type argument play.api.libs.json.JsObject in type pattern List[play.api.libs.json.JsObject] is unchecked since it is eliminated by erasure
[warn]     (clustersActor ? NotebookClusters.Profiles).map { case all: List[JsObject] =>
[warn]                                                                 ^
[warn] /Users/umit/Desktop/+Spark_Notebook/spark-notebook/app/controllers/Application.scala:259: non-variable type argument play.api.libs.json.JsObject in type pattern List[play.api.libs.json.JsObject] is unchecked since it is eliminated by erasure
[warn]     (clustersActor ? NotebookClusters.All).map { case all: List[JsObject] =>
[warn]                                                            ^
[warn] /Users/umit/Desktop/+Spark_Notebook/spark-notebook/app/controllers/Application.scala:338: `withFilter' method does not yet exist on scala.util.Try[play.api.libs.json.JsValue], using `filter' method instead
[warn]       j <- Try(custom \ "customSparkConf") if j.isInstanceOf[JsObject]
[warn]               ^
[warn] three warnings found
[success] Total time: 219 s, completed Jan 12, 2017 11:22:37 AM
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Compiling 1 Scala source to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/common/target/scala-2.10/classes...

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/umit/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/umit/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
--- (Running the application, auto-reloading is enabled) ---

log4j:WARN No appenders could be found for logger (org.jboss.netty.channel.socket.nio.SelectorUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

(Server started, use Ctrl+D to stop and go back to the console...)

[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Compiling 1 Scala source to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/common/target/scala-2.10/classes...
[info] CoffeeScript compiling on 21 source(s)
[info] LESS compiling on 2 source(s)
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Compiling 1 Scala source to /Users/umit/Desktop/+Spark_Notebook/spark-notebook/modules/common/target/scala-2.10/classes...
[DEBUG] [01/12/2017 11:23:38.697] [New I/O worker #1] [EventStream] StandardOutLogger started
[DEBUG] [01/12/2017 11:23:38.901] [New I/O worker #1] [EventStream(akka://NotebookServer)] logger log1-Slf4jLogger started
[DEBUG] [01/12/2017 11:23:38.902] [New I/O worker #1] [EventStream(akka://NotebookServer)] Default Loggers started
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0
Error: Could not find or load main class notebook.kernel.pfork.ChildProcessMain
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vidma** [comment]
you have a weird dir name: `/Users/umit/Desktop/+Spark_Notebook/spark-notebook/`
just remove the '+' from your path, and recompile ;) I got the same issue when I renamed the directory to `+Spark_Notebook`.

the `+`  doesn't get escaped properly, and thus the classpath of REPL process doesn't contain the required libs.

**Comment by Umit-Mert** [comment]
yes, that was it. Thank you so much!
