### ISSUE TITLE
Read Only --> Locking cells

### ISSUE THREAD

**Issue by quertenmont** [andypetrella/spark-notebook#789]
Hello,

Can we prevent the user to do any actions in the SNB when open in read only?
I just spent sometime working in my notebook (moving cells, editing cells, etc) until I realize that I can't execute it neither save it, because it was open in read only mode.

For me it would be good to have the cells locked for editing/moving when opened in read only,
so we can realize immediately that we can't actually change this SNB.

Loic,

**Comment by vidma** [comment]
good point! let's start by `locking cell editing in read-only mode` (current problem is that you can change cells but can not save) !


though, I'm not sure what should be the ideal behaviour. maybe we need different concepts:
- if notebook is attached to cluster/kernel/repl
- if notebook is editable

**Comment by vidma** [comment]
fixed in #812
