### ISSUE TITLE
Non-interactive dependency pull?

### ISSUE THREAD

**Issue by dserban** [andypetrella/spark-notebook#816]
Is there a way to execute a `:dp` dependency pull non-interactively, as a bash script, inside of a Spark Notebook Docker container?
(The equivalent of adding a new entry to `build.sbt` and then running `sbt update`)

**Comment by maasg** [comment]
The best way to manage dependencies is to edit your metadata and add two things:
  - "customLocalRepo": Specify a local directory as repository. You could point it directly to your local ivy cache.
  - "customDependencies": Add here the dependencies you require. For example, I added `circe` to my notebook:
```
  "customDeps": [
    "org.scalaj %% scalaj-http % 2.3.0",
    "io.circe %% circe-core % 0.7.0",
    "io.circe %% circe-generic % 0.7.0",
    "io.circe %% circe-parser % 0.7.0",
    "io.circe %% circe-optics % 0.7.0"
  ],
```
Does this help?

**Comment by dserban** [comment]
@maasg Yes, this is what I was looking for, thank you.
