### ISSUE TITLE
source of the examples data file in the widgets documentation

### ISSUE THREAD

**Issue by dportabella** [andypetrella/spark-notebook#822]
This documentation about the graphical widgets is excellent:
https://github.com/andypetrella/spark-notebook/blob/431b35335d65cb6d8107c82497a9307fb6a9cb97/docs/widgets_viz.md

Can you please tell us the source of the "examples" data file?

and you read it as follows?
`val examples: DataFrame = spark.read.json("path/to/examples.json")
`

**Comment by maasg** [comment]
If I remember correctly, the source of the example charts should be this notebook: 
https://github.com/kensuio/scala-for-data-science/blob/master/notebooks/Why%20Spark%20Notebook.snb

`example` was a randomly generated dataset but you can read data from a file like you say.

**Comment by dportabella** [comment]
cool, thx.
